-- Seed google_crawler_state: insert all 204 enabled markets from google_markets.yml
-- Existing rows are untouched (WHERE NOT EXISTS).
-- New rows get status='pending', updated_at='2000-01-01' so heartbeat shows gray (never run).
INSERT INTO google_crawler_state
  (gl, hl, status, current_depth, processed, queries_total, new_total, updated_at)
SELECT v.gl, v.hl, 'pending', 0, 0, 0, 0, '2000-01-01 00:00:00+00'
FROM (VALUES ('ad', 'ca'), ('ae', 'ar'), ('af', 'ps'), ('ag', 'en'), ('ai', 'en'), ('al', 'sq'), ('am', 'hy'), ('ao', 'pt'), ('ar', 'es'), ('as', 'en'), ('at', 'de'), ('au', 'en'), ('az', 'az'), ('ba', 'bs'), ('bd', 'bn'), ('be', 'fr'), ('be', 'nl'), ('bf', 'fr'), ('bg', 'bg'), ('bh', 'ar'), ('bi', 'fr'), ('bj', 'fr'), ('bn', 'ms'), ('bo', 'es'), ('br', 'pt'), ('bs', 'en'), ('bt', 'dz'), ('bw', 'en'), ('by', 'be'), ('bz', 'en'), ('ca', 'en'), ('ca', 'fr'), ('cd', 'fr'), ('cf', 'fr'), ('cg', 'fr'), ('ch', 'de'), ('ch', 'fr'), ('ch', 'it'), ('ci', 'fr'), ('ck', 'en'), ('cl', 'es'), ('cm', 'fr'), ('cn', 'zh-CN'), ('co', 'es'), ('cr', 'es'), ('cu', 'es'), ('cv', 'pt'), ('cy', 'el'), ('cz', 'cs'), ('de', 'de'), ('dj', 'fr'), ('dk', 'da'), ('dm', 'en'), ('do', 'es'), ('dz', 'ar'), ('ec', 'es'), ('ee', 'et'), ('eg', 'ar'), ('er', 'ti'), ('es', 'es'), ('et', 'am'), ('fi', 'fi'), ('fj', 'en'), ('fm', 'en'), ('fo', 'fo'), ('fr', 'fr'), ('ga', 'fr'), ('ge', 'ka'), ('gf', 'fr'), ('gg', 'en'), ('gh', 'en'), ('gi', 'en'), ('gl', 'kl'), ('gm', 'en'), ('gp', 'fr'), ('gq', 'es'), ('gr', 'el'), ('gt', 'es'), ('gw', 'pt'), ('gy', 'en'), ('hk', 'zh-TW'), ('hn', 'es'), ('hr', 'hr'), ('ht', 'fr'), ('hu', 'hu'), ('id', 'id'), ('ie', 'en'), ('il', 'iw'), ('im', 'en'), ('in', 'hi'), ('iq', 'ar'), ('ir', 'fa'), ('is', 'is'), ('it', 'it'), ('je', 'en'), ('jm', 'en'), ('jo', 'ar'), ('jp', 'ja'), ('ke', 'sw'), ('kg', 'ky'), ('kh', 'km'), ('ki', 'en'), ('kp', 'ko'), ('kr', 'ko'), ('kw', 'ar'), ('kz', 'kk'), ('la', 'lo'), ('lb', 'ar'), ('lc', 'en'), ('li', 'de'), ('lk', 'si'), ('ls', 'en'), ('lt', 'lt'), ('lu', 'fr'), ('lv', 'lv'), ('ly', 'ar'), ('ma', 'ar'), ('mc', 'fr'), ('md', 'ro'), ('me', 'sr'), ('mg', 'mg'), ('ml', 'fr'), ('mm', 'my'), ('mn', 'mn'), ('mo', 'zh-TW'), ('ms', 'en'), ('mt', 'mt'), ('mu', 'en'), ('mv', 'dv'), ('mw', 'en'), ('mx', 'es'), ('my', 'ms'), ('mz', 'pt'), ('na', 'en'), ('ne', 'fr'), ('ng', 'en'), ('ni', 'es'), ('nl', 'nl'), ('no', 'no'), ('np', 'ne'), ('nr', 'en'), ('nu', 'en'), ('nz', 'en'), ('om', 'ar'), ('pa', 'es'), ('pe', 'es'), ('pg', 'en'), ('ph', 'tl'), ('pk', 'ur'), ('pl', 'pl'), ('pr', 'es'), ('ps', 'ar'), ('pt', 'pt'), ('py', 'es'), ('qa', 'ar'), ('ro', 'ro'), ('rs', 'sr'), ('ru', 'ru'), ('rw', 'rw'), ('sa', 'ar'), ('sb', 'en'), ('sc', 'fr'), ('se', 'sv'), ('sg', 'en'), ('sh', 'en'), ('si', 'sl'), ('sk', 'sk'), ('sl', 'en'), ('sm', 'it'), ('sn', 'fr'), ('so', 'so'), ('sr', 'nl'), ('st', 'pt'), ('sv', 'es'), ('sy', 'ar'), ('td', 'fr'), ('tg', 'fr'), ('th', 'th'), ('tj', 'tg'), ('tk', 'en'), ('tl', 'pt'), ('tm', 'tk'), ('tn', 'ar'), ('to', 'to'), ('tr', 'tr'), ('tt', 'en'), ('tw', 'zh-TW'), ('tz', 'sw'), ('ua', 'uk'), ('ug', 'en'), ('uk', 'en'), ('us', 'en'), ('uy', 'es'), ('uz', 'uz'), ('vc', 'en'), ('ve', 'es'), ('vg', 'en'), ('vi', 'en'), ('vn', 'vi'), ('vu', 'bi'), ('ws', 'sm'), ('za', 'af'), ('zm', 'en'), ('zw', 'en')) AS v(gl, hl)
WHERE NOT EXISTS (
  SELECT 1 FROM google_crawler_state cs
  WHERE cs.gl = v.gl AND cs.hl = v.hl
);
