export type TocEntry = { id: string; level: 1 | 2; title: string };

export const TOC: TocEntry[] = [
  { id: 'seznam-veci', level: 1, title: 'Seznam věcí k vyřešení' },
  { id: 'vozidla', level: 2, title: 'Vozidla a přeprava' },
  { id: 'nabytek', level: 2, title: 'Velký nábytek' },
  { id: 'spotrebice', level: 2, title: 'Spotřebiče a elektronika' },
  { id: 'zvirata', level: 2, title: 'Zvířata k dořešení' },
  { id: 'akvaria', level: 2, title: 'Akvária a chovatelské vybavení' },
  { id: 'zahrada', level: 2, title: 'Zahrada, dílna a venkovní vybavení' },
  { id: 'ostatni', level: 2, title: 'Ostatní věci' },
  { id: 'overit-pronajimatelka', level: 2, title: 'Ověřit s pronajímatelkou / opravit před předáním' },
  { id: 'financni-souhrn', level: 1, title: 'Finanční souhrn nájmu' },
  { id: 'posledni-najem', level: 2, title: 'Poslední nájem při skončení 6. 10. 2026' },
  { id: 'co-udelat-ted', level: 1, title: 'Co udělat teď' },
  { id: 'vzor-oznameni', level: 1, title: 'Vzor oznámení' },
  { id: 'smlouva', level: 1, title: 'Co říká přiložená smlouva' },
  { id: 'harmonogram', level: 1, title: 'Harmonogram' },
  { id: 'harmonogram-do-25-8', level: 2, title: 'Do 25. 8. 2026' },
  { id: 'harmonogram-zari', level: 2, title: 'Září 2026' },
  { id: 'harmonogram-predani', level: 2, title: 'Při předání, nejpozději 6. 10. 2026' },
  { id: 'harmonogram-po-predani', level: 2, title: 'Po předání' },
  { id: 'pravni-rozbor', level: 1, title: 'Právní rozbor podle skutečného průběhu nájmu' },
  { id: 'skutecny-prubeh', level: 2, title: 'Skutečný průběh' },
  { id: 'platnost-ustnich', level: 2, title: 'Platnost ústních prodloužení' },
  { id: 'rekreacni-stavba', level: 2, title: 'Rekreační stavba používaná k bydlení' },
  { id: 'kontrola-smlouvy', level: 2, title: 'Kontrola původní smlouvy podle současného práva' },
  { id: 'vetsi-opravy', level: 2, title: 'Větší opravy a zápočty proti nájemnému' },
  { id: 'zvysene-najemne', level: 2, title: 'Ústně zvýšené nájemné 25 000 Kč' },
  { id: 'davka-bydleni', level: 2, title: 'Dávka na bydlení a zdanění nájemného' },
  { id: 'co-musi-byt-v-dohode', level: 2, title: 'Co musí být v písemné dohodě o skončení' },
  { id: 'pravni-zdroje', level: 2, title: 'Právní zdroje' },
  { id: 'dulezite-upozorneni', level: 1, title: 'Důležité právní upozornění' },
  { id: 'podklady-zdroje', level: 1, title: 'Podklady a zdroje' },
];
