import { GEOCODED } from "./coords.generated";
import type { Place } from "./types";

/**
 * Karta bez mapového bodu. Souřadnice se do karty doplňují výhradně z `coords.generated.ts`,
 * tedy z jednorázového geokódování podle D01-A (zadání korfu2026-02, bod 1).
 * D01-A bylo v sekci 26 SOURCE_PACKu, která byla odstraněna (SOURCE_PACK = 478 ř.);
 * autoritativní text D01-A je v zadání korfu2026-02, bod 1. V tomto souboru se souřadnice nikdy nepíšou ručně.
 */
type PlaceSeed = Omit<
  Place,
  | "coords"
  | "coordsStatus"
  | "coordsNote"
  | "coordsSource"
  | "coordsQuery"
  | "coordsCheckedAt"
  | "weatherFit"
  | "transportModes"
  | "difficulty"
  | "facts"
  | "sourceException"
> & {
  weatherFit?: Place["weatherFit"];
  transportModes?: Place["transportModes"];
  difficulty?: Place["difficulty"];
  facts?: Place["facts"];
  /** Autorova výjimka musí být přímo u seedu; doplňování za běhu je zakázané. */
  sourceException?: Place["sourceException"];
};

/**
 * Katalog karet — Korfu 2026.
 *
 * ZDROJ: výhradně .korfu/SOURCE_PACK.md (verze po druhém úplném reauditu, 13. 9. 2026).
 * Každá karta nese v poli `sp` čísla řádků SOURCE_PACKu, ze kterých je doložená.
 * Hodnota, kterou SOURCE_PACK neuvádí, zůstává `null` / prázdné pole (kontrakt bod 16).
 *
 * MAPOVÉ BODY (mezera G1 → vyřešeno direktivou):
 * Části 1–25 SOURCE_PACKu neobsahují ani jednu číselnou souřadnici (ověřeno grepem na
 * `[0-9]{1,2}\.[0-9]{4,}` a na `°` — jediné zásahy jsou teploty v ř. 349).
 * D01-A (zadání korfu2026-02, bod 1) proto povolilo jednorázové geokódování přes
 * OpenStreetMap Nominatim. Výsledek je staticky uložený v `coords.generated.ts` a doplňuje se
 * do karet funkcí `withGeocode()` níže. Ručně psané souřadnice jsou v tomto souboru zakázané.
 *
 * PRAVIDLO R-NAV:
 * `mapsQuery` = první varianta názvu z části 6 + `, Korfu`. Je-li bod ověřený, Navigovat míří
 * na souřadnice; u neověřitelného bodu zůstává Google Maps vyhledávání podle názvu
 * (D01-A, zadání korfu2026-02).
 *
 * POŘADÍ: přesně podle číslovaného ručního seznamu v části 6 (ř. 56–71).
 */

/** 13 ručních must-see míst — SOURCE_PACK část 6, ř. 55–72. */
const MUST_SEE_SEEDS: PlaceSeed[] = [
  {
    id: "canal-damour",
    canonicalName: "Canal d'Amour u Sidari",
    czName: null,
    category: "plaz",
    subcategory: "pískovcové útvary a kanály",
    tier: "must-see",
    area: "severozapad",
    why: "Ruční seznam, priorita č. 1. Pískovcové útvary a kanály na severozápadním pobřeží u Sidari.",
    wow: null,
    userPriority: "Očíslovaná priorita č. 1 (ruční seznam)",
    visitDuration: null,
    bestPartOfDay: null,
    weather: null,
    transport: [],
    accessDifficulty: null,
    parking: null,
    combinesWith: ["Sidari / Canal d’Amour / Cape Drastis / Loggas"],
    warnings: ["Za větru a vln opatrnost."],
    timeFromHotel: null,
    mapsQuery: "Canal d'Amour, Sidari, Korfu",
    sources: [],
    sourceException: {
      reason: "SOURCE_PACK uvádí Canal d'Amour u Sidari jako katalogovou položku v citovaných řádcích; nepřiřazuje mu však konkrétní oficiální ani ověřovací URL, proto nebyl odkaz doplněn odhadem.",
      sp: "SP:57, SP:80, SP:116, SP:413",
    },
    verify: [],
    sp: "SP:57, SP:80, SP:116, SP:413",
  },
  {
    id: "porto-timoni",
    canonicalName: "Porto Timoni",
    czName: null,
    category: "plaz",
    subcategory: "dvojitá pláž",
    tier: "must-see",
    area: "severozapad",
    why: "Ruční seznam, priorita č. 2 — dvojitá pláž, v poznámce označena srdcem. Pěší sestup z Afionasu, nebo příjezd lodí.",
    wow: null,
    userPriority: "Očíslovaná priorita č. 2, „označena srdcem“ (ruční seznam)",
    visitDuration: null,
    bestPartOfDay: null,
    weather: "Za mokra problematické.",
    transport: [
      "Pěší sestup z Afionasu.",
      "Lodí — z Agios Georgios Pagon i bez pěšího sestupu.",
    ],
    accessDifficulty: "Strmá kamenitá cesta.",
    parking: null,
    combinesWith: ["Afionas / Porto Timoni / Agios Georgios Pagon"],
    warnings: [
      "Strmá kamenitá cesta.",
      "Za mokra označeno jako problematické.",
    ],
    timeFromHotel: null,
    mapsQuery: "Porto Timoni, Korfu",
    sources: [],
    sourceException: {
      reason: "SOURCE_PACK uvádí Porto Timoni jako katalogovou položku v citovaných řádcích; nepřiřazuje mu však konkrétní oficiální ani ověřovací URL, proto nebyl odkaz doplněn odhadem.",
      sp: "SP:58, SP:82–83, SP:117, SP:200, SP:353, SP:414",
    },
    verify: [],
    sp: "SP:58, SP:82–83, SP:117, SP:200, SP:353, SP:414",
  },
  {
    id: "paleokastritsa",
    canonicalName: "Paleokastritsa / Palaiokastritsa",
    czName: null,
    category: "plaz",
    subcategory: "zátoky, klášter, jeskyně",
    tier: "must-see",
    area: "zapad",
    why: "Ruční seznam, priorita č. 3. Zátoky, klášter, jeskyně, krátké plavby i vlastní loď. Nejdramatičtější scenérie a nejvíc jeskyní a boat-only pláží.",
    wow: null,
    userPriority: "Očíslovaná priorita č. 3 (ruční seznam)",
    visitDuration: null,
    bestPartOfDay: null,
    weather: null,
    transport: ["Krátké plavby i vlastní loď."],
    accessDifficulty: null,
    parking: null,
    combinesWith: [
      "Paleokastritsa / Liapades / Rovinia / Angelokastro nebo Lakones",
    ],
    warnings: [],
    timeFromHotel: null,
    mapsQuery: "Paleokastritsa, Korfu",
    sources: [],
    sourceException: {
      reason: "SOURCE_PACK uvádí Paleokastritsa / Palaiokastritsa jako katalogovou položku v citovaných řádcích; nepřiřazuje mu však konkrétní oficiální ani ověřovací URL, proto nebyl odkaz doplněn odhadem.",
      sp: "SP:59, SP:84–85, SP:101, SP:118, SP:183–185, SP:221, SP:417",
    },
    verify: [
      {
        what: "Orientační cena bezlicenční lodi v Paleokastritse: cca od 100 €, často bez paliva — ověřit aktuálně.",
        sp: "SP:220–221",
        source: null,
      },
    ],
    sp: "SP:59, SP:84–85, SP:101, SP:118, SP:183–185, SP:221, SP:417",
  },
  {
    id: "kassiopi-beach",
    canonicalName: "Kassiopi Beach",
    czName: null,
    category: "plaz",
    subcategory: "pláž, přístav a hrad",
    tier: "must-see",
    area: "severovychod",
    why: "Ruční seznam. Kromě pláže i přístav, hrad a restaurace; blízké pláže v okolí.",
    wow: null,
    userPriority: null,
    visitDuration: null,
    bestPartOfDay: null,
    weather: null,
    transport: [],
    accessDifficulty: null,
    parking: null,
    combinesWith: ["Kassiopi / Avlaki / Kerasia / Kouloura / Kalami / Agni"],
    warnings: [],
    timeFromHotel: null,
    mapsQuery: "Kassiopi, Korfu",
    sources: [],
    sourceException: {
      reason: "SOURCE_PACK uvádí Kassiopi Beach jako katalogovou položku v citovaných řádcích; nepřiřazuje mu však konkrétní oficiální ani ověřovací URL, proto nebyl odkaz doplněn odhadem.",
      sp: "SP:61–62, SP:89, SP:98, SP:119, SP:416",
    },
    verify: [
      {
        what: "Ověřit, zda „Kassiopi Beach“ nejlépe odpovídá Bataria, Kanoni nebo jiné konkrétní pláži — přesný výběr ověřit.",
        sp: "SP:61–62, SP:89",
        source: null,
      },
    ],
    sp: "SP:61–62, SP:89, SP:98, SP:119, SP:416",
  },
  {
    id: "rovinia-beach",
    canonicalName: "Rovinia Beach",
    czName: null,
    category: "plaz",
    subcategory: null,
    tier: "must-see",
    area: "zapad",
    why: "Ruční seznam. Západní pobřeží u Paleokastritsy; dostupná pěšky i z vody.",
    wow: null,
    userPriority: null,
    visitDuration: null,
    bestPartOfDay: null,
    weather: null,
    transport: ["Pěšky i z vody."],
    accessDifficulty: null,
    parking: null,
    combinesWith: [
      "Paleokastritsa / Liapades / Rovinia / Angelokastro nebo Lakones",
    ],
    warnings: [],
    timeFromHotel: null,
    mapsQuery: "Rovinia Beach, Korfu",
    sources: [],
    sourceException: {
      reason: "SOURCE_PACK uvádí Rovinia Beach jako katalogovou položku v citovaných řádcích; nepřiřazuje mu však konkrétní oficiální ani ověřovací URL, proto nebyl odkaz doplněn odhadem.",
      sp: "SP:63, SP:84–85, SP:118, SP:184",
    },
    verify: [],
    sp: "SP:63, SP:84–85, SP:118, SP:184",
  },
  {
    id: "agios-gordios",
    canonicalName: "Agios Gordios",
    czName: null,
    category: "plaz",
    subcategory: "pláž, vesnice a panorama",
    tier: "must-see",
    area: "zapad",
    why: "Ruční seznam — vesnice, pláž a panorama. Panoramatické pohledy.",
    wow: null,
    userPriority: null,
    visitDuration: null,
    bestPartOfDay: null,
    weather: null,
    transport: [],
    accessDifficulty: null,
    parking: null,
    combinesWith: ["Myrtiotissa / Pelekas / Agios Gordios"],
    warnings: [],
    timeFromHotel: null,
    mapsQuery: "Agios Gordios, Korfu",
    sources: [],
    sourceException: {
      reason: "SOURCE_PACK uvádí Agios Gordios jako katalogovou položku v citovaných řádcích; nepřiřazuje mu však konkrétní oficiální ani ověřovací URL, proto nebyl odkaz doplněn odhadem.",
      sp: "SP:64, SP:88, SP:102, SP:122",
    },
    verify: [],
    sp: "SP:64, SP:88, SP:102, SP:122",
  },
  {
    id: "issos-beach",
    canonicalName: "Issos Beach",
    czName: null,
    category: "plaz",
    subcategory: null,
    tier: "must-see",
    area: "jih-jihozapad",
    why: "Ruční seznam — v poznámce označena hvězdičkou, tedy viditelně silné přání. V katalogu pláží vedena jako výrazná uživatelská priorita.",
    wow: null,
    userPriority:
      "„Označena hvězdičkou = viditelně silné přání“ (ruční seznam)",
    visitDuration: null,
    bestPartOfDay: null,
    weather: null,
    transport: [],
    accessDifficulty: null,
    parking: null,
    combinesWith: ["Chalikounas / Lake Korission / Issos"],
    warnings: [],
    timeFromHotel: null,
    mapsQuery: "Issos Beach, Korfu",
    sources: [],
    sourceException: {
      reason: "SOURCE_PACK uvádí Issos Beach jako katalogovou položku v citovaných řádcích; nepřiřazuje mu však konkrétní oficiální ani ověřovací URL, proto nebyl odkaz doplněn odhadem.",
      sp: "SP:65, SP:92–93, SP:123",
    },
    verify: [],
    sp: "SP:65, SP:92–93, SP:123",
  },
  {
    id: "avlaki-beach",
    canonicalName: "Avlaki Beach",
    czName: null,
    category: "plaz",
    subcategory: null,
    tier: "must-see",
    area: "severovychod",
    why: "Ruční seznam. Severovýchodní pobřeží v sousedství Kassiopi a Kerasie.",
    wow: null,
    userPriority: null,
    visitDuration: null,
    bestPartOfDay: null,
    weather: null,
    transport: [],
    accessDifficulty: null,
    parking: null,
    combinesWith: ["Kassiopi / Avlaki / Kerasia / Kouloura / Kalami / Agni"],
    warnings: [],
    timeFromHotel: null,
    mapsQuery: "Avlaki Beach, Korfu",
    sources: [],
    sourceException: {
      reason: "SOURCE_PACK uvádí Avlaki Beach jako katalogovou položku v citovaných řádcích; nepřiřazuje mu však konkrétní oficiální ani ověřovací URL, proto nebyl odkaz doplněn odhadem.",
      sp: "SP:66, SP:89, SP:119, SP:413",
    },
    verify: [],
    sp: "SP:66, SP:89, SP:119, SP:413",
  },
  {
    id: "marathias-beach",
    canonicalName: "Marathias Beach",
    czName: null,
    category: "plaz",
    subcategory: null,
    tier: "must-see",
    area: "jih-jihozapad",
    why: "Ruční seznam. Jih a jihozápad ostrova, v sousedství Issosu a klidnějšího pobřeží u Boukari a Petriti.",
    wow: null,
    userPriority: null,
    visitDuration: null,
    bestPartOfDay: null,
    weather: null,
    transport: [],
    accessDifficulty: null,
    parking: null,
    combinesWith: ["Marathias / Boukari / Petriti"],
    warnings: [],
    timeFromHotel: null,
    mapsQuery: "Marathias Beach, Korfu",
    sources: [],
    sourceException: {
      reason: "SOURCE_PACK uvádí Marathias Beach jako katalogovou položku v citovaných řádcích; nepřiřazuje mu však konkrétní oficiální ani ověřovací URL, proto nebyl odkaz doplněn odhadem.",
      sp: "SP:67, SP:92, SP:124",
    },
    verify: [],
    sp: "SP:67, SP:92, SP:124",
  },
  {
    id: "nissaki-beach",
    canonicalName: "Nissaki Beach",
    czName: null,
    category: "plaz",
    subcategory: null,
    tier: "must-see",
    area: "severovychod",
    why: "Ruční seznam. Severovýchodní pobřeží s krátkými vzdálenostmi mezi zátokami — Nissaki, Kaminaki, Agni, Kalami, Kouloura, Kerasia.",
    wow: null,
    userPriority: null,
    visitDuration: null,
    bestPartOfDay: null,
    weather: null,
    transport: [],
    accessDifficulty: null,
    parking: null,
    combinesWith: ["Nissaki / Kaminaki / Barbati / Ipsos"],
    warnings: [],
    timeFromHotel: null,
    mapsQuery: "Nissaki Beach, Korfu",
    sources: [],
    sourceException: {
      reason: "SOURCE_PACK uvádí Nissaki Beach jako katalogovou položku v citovaných řádcích; nepřiřazuje mu však konkrétní oficiální ani ověřovací URL, proto nebyl odkaz doplněn odhadem.",
      sp: "SP:68, SP:91, SP:120, SP:194–198, SP:221–222",
    },
    verify: [
      {
        what: "Orientační cena bezlicenční lodi v Nissaki od 16. 9.: cca 80–170 € podle lodi, často bez paliva — ověřit aktuálně.",
        sp: "SP:220–223",
        source: null,
      },
    ],
    sp: "SP:68, SP:91, SP:120, SP:194–198, SP:221–222",
  },
  {
    id: "chalikounas-beach",
    canonicalName: "Chalikounas / Halikounas Beach",
    czName: null,
    category: "plaz",
    subcategory: null,
    tier: "must-see",
    area: "jih-jihozapad",
    why: "Ruční seznam. Jihozápadní pobřeží; Lake Korission je přírodní spojnice mezi Chalikounas a Issos.",
    wow: null,
    userPriority: null,
    visitDuration: null,
    bestPartOfDay: null,
    weather: null,
    transport: [],
    accessDifficulty: null,
    parking: null,
    combinesWith: ["Chalikounas / Lake Korission / Issos"],
    warnings: [],
    timeFromHotel: null,
    mapsQuery: "Chalikounas Beach, Korfu",
    sources: [],
    sourceException: {
      reason: "SOURCE_PACK uvádí Chalikounas / Halikounas Beach jako katalogovou položku v citovaných řádcích; nepřiřazuje mu však konkrétní oficiální ani ověřovací URL, proto nebyl odkaz doplněn odhadem.",
      sp: "SP:69, SP:92–93, SP:123",
    },
    verify: [],
    sp: "SP:69, SP:92–93, SP:123",
  },
  {
    id: "myrtiotissa-beach",
    canonicalName: "Myrtiotissa Beach",
    czName: null,
    category: "plaz",
    subcategory: null,
    tier: "must-see",
    area: "zapad",
    why: "Ruční seznam. Západní pobřeží mezi Paleokastritsou a Agios Gordios.",
    wow: null,
    userPriority: null,
    visitDuration: null,
    bestPartOfDay: null,
    weather: "Za mokra problematické.",
    transport: [],
    accessDifficulty: null,
    parking: null,
    combinesWith: ["Myrtiotissa / Pelekas / Agios Gordios"],
    warnings: ["Za mokra označeno jako problematické."],
    timeFromHotel: null,
    mapsQuery: "Myrtiotissa Beach, Korfu",
    sources: [],
    sourceException: {
      reason: "SOURCE_PACK uvádí Myrtiotissa Beach jako katalogovou položku v citovaných řádcích; nepřiřazuje mu však konkrétní oficiální ani ověřovací URL, proto nebyl odkaz doplněn odhadem.",
      sp: "SP:70, SP:87–88, SP:122, SP:353",
    },
    verify: [
      {
        what: "Ověřit přístup, parkování, sestup a aktuální charakter pláže.",
        sp: "SP:87–88",
        source: null,
      },
    ],
    sp: "SP:70, SP:87–88, SP:122, SP:353",
  },
  {
    id: "barbati-beach",
    canonicalName: "Barbati Beach",
    czName: null,
    category: "plaz",
    subcategory: null,
    tier: "must-see",
    area: "severovychod",
    why: "Ruční seznam. Severovýchodní pobřeží v linii Nissaki – Kaminaki – Barbati – Ipsos.",
    wow: null,
    userPriority: null,
    visitDuration: null,
    bestPartOfDay: null,
    weather: null,
    transport: [],
    accessDifficulty: null,
    parking: null,
    combinesWith: ["Nissaki / Kaminaki / Barbati / Ipsos"],
    warnings: [],
    timeFromHotel: null,
    mapsQuery: "Barbati Beach, Korfu",
    sources: [],
    sourceException: {
      reason: "SOURCE_PACK uvádí Barbati Beach jako katalogovou položku v citovaných řádcích; nepřiřazuje mu však konkrétní oficiální ani ověřovací URL, proto nebyl odkaz doplněn odhadem.",
      sp: "SP:71, SP:91, SP:120, SP:210",
    },
    verify: [],
    sp: "SP:71, SP:91, SP:120, SP:210",
  },
];

/**
 * Doplní mapový bod z `coords.generated.ts`. Chybí-li záznam, karta zůstane bez bodu —
 * nikdy se nedosazuje odhad (D01-A, zadání korfu2026-02).
 */
function withGeocode(seed: PlaceSeed): Place {
  const hasSource = seed.sources.length > 0;
  const hasException = seed.sourceException !== undefined && seed.sourceException !== null;

  if (hasSource === hasException) {
    throw new Error(
      `Neplatná provenience karty ${seed.id}: vyžaduje právě jeden z sources nebo sourceException.`,
    );
  }

  const base = {
    weatherFit: seed.weatherFit ?? [],
    transportModes: seed.transportModes ?? [],
    difficulty: seed.difficulty ?? null,
    facts: seed.facts ?? [],
    sourceException: hasException ? seed.sourceException! : null,
  };
  const g = GEOCODED[seed.id];
  if (!g) {
    return {
      ...seed,
      ...base,
      coords: null,
      coordsStatus: "chybi-ve-zdroji",
      coordsNote: "Mapový bod zatím nebyl dohledán.",
      coordsSource: null,
      coordsQuery: null,
      coordsCheckedAt: null,
    };
  }
  return {
    ...seed,
    ...base,
    coords: g.coords,
    coordsStatus: g.coordsStatus,
    coordsNote:
      g.coordsStatus === "overene"
        ? null
        : "Mapový bod se nepodařilo jednoznačně dohledat — Navigovat otevře vyhledávání podle názvu.",
    coordsSource: g.coordsSource,
    coordsQuery: g.coordsQuery,
    coordsCheckedAt: g.coordsCheckedAt,
  };
}

// ─── Zbývající pláže (část 7, SP:74–94) — 27 míst bez must-see ───────────────

/** Pláže blízko základny — SP:75–79. */
const BEACH_SEEDS_ZAKLADNA: PlaceSeed[] = [
  {
    id: "roda-beach",
    canonicalName: "Roda Beach",
    czName: null,
    category: "zakladna",
    subcategory: "hotelová pláž, bary, vodní aktivity",
    tier: "doporuceni",
    area: "blizko-zakladny",
    why: "Nejjednodušší koupání přímo u hotelu — bary, lehátka, vodní aktivity. Základna celé cesty.",
    wow: null,
    userPriority: null,
    visitDuration: null,
    bestPartOfDay: null,
    weather: null,
    weatherFit: [],
    transport: [],
    transportModes: [],
    accessDifficulty: null,
    difficulty: null,
    parking: null,
    combinesWith: [
      "Roda / Apollónův chrám / Roda Loop nebo pobřežní procházka / Acharavi / Almyros",
    ],
    warnings: [],
    timeFromHotel: null,
    mapsQuery: "Roda Beach, Korfu",
    sources: [],
    sourceException: {
      reason: "SOURCE_PACK uvádí Roda Beach jako katalogovou položku v citovaných řádcích; nepřiřazuje mu však konkrétní oficiální ani ověřovací URL, proto nebyl odkaz doplněn odhadem.",
      sp: "SP:75, SP:293",
    },
    verify: [
      {
        what: "Po polovině září ověřit provoz vodních aktivit.",
        sp: "SP:75",
        source: null,
      },
    ],
    facts: [],
    sp: "SP:75, SP:293",
  },
  {
    id: "acharavi-beach",
    canonicalName: "Acharavi Beach",
    czName: null,
    category: "plaz",
    subcategory: "dlouhá pláž, promenáda",
    tier: "doporuceni",
    area: "blizko-zakladny",
    why: "Dlouhá pláž, promenáda, obchody, kavárny. Dobrá i na podvečerní procházku.",
    wow: null,
    userPriority: null,
    visitDuration: null,
    bestPartOfDay: null,
    weather: null,
    weatherFit: [],
    transport: [],
    transportModes: [],
    accessDifficulty: null,
    difficulty: null,
    parking: null,
    combinesWith: [
      "Roda / Apollónův chrám / Roda Loop nebo pobřežní procházka / Acharavi / Almyros",
    ],
    warnings: [],
    timeFromHotel: null,
    mapsQuery: "Acharavi Beach, Korfu",
    sources: [],
    sourceException: {
      reason: "SOURCE_PACK uvádí Acharavi Beach jako katalogovou položku v citovaných řádcích; nepřiřazuje mu však konkrétní oficiální ani ověřovací URL, proto nebyl odkaz doplněn odhadem.",
      sp: "SP:76",
    },
    verify: [],
    facts: [],
    sp: "SP:76",
  },
  {
    id: "almyros-beach",
    canonicalName: "Almyros Beach",
    czName: null,
    category: "plaz",
    subcategory: "dlouhý severní úsek",
    tier: "doporuceni",
    area: "blizko-zakladny",
    why: "Dlouhý severní úsek; souvisí s jezdeckými trasami (Antinioti, Cape Ekaterini).",
    wow: null,
    userPriority: null,
    visitDuration: null,
    bestPartOfDay: null,
    weather: null,
    weatherFit: [],
    transport: [],
    transportModes: [],
    accessDifficulty: null,
    difficulty: null,
    parking: null,
    combinesWith: [
      "Roda / Apollónův chrám / Roda Loop nebo pobřežní procházka / Acharavi / Almyros",
    ],
    warnings: [],
    timeFromHotel: null,
    mapsQuery: "Almyros Beach, Korfu",
    sources: [],
    sourceException: {
      reason: "SOURCE_PACK uvádí Almyros Beach jako katalogovou položku v citovaných řádcích; nepřiřazuje mu však konkrétní oficiální ani ověřovací URL, proto nebyl odkaz doplněn odhadem.",
      sp: "SP:77",
    },
    verify: [],
    facts: [],
    sp: "SP:77",
  },
  {
    id: "agios-spiridon-beach",
    canonicalName: "Agios Spiridon Beach",
    czName: null,
    category: "plaz",
    subcategory: "pláž, příroda, Antinioti",
    tier: "doporuceni",
    area: "blizko-zakladny",
    why: "Koupání, příroda, Antinioti laguna, jezdecké aktivity.",
    wow: null,
    userPriority: null,
    visitDuration: null,
    bestPartOfDay: null,
    weather: null,
    weatherFit: [],
    transport: [],
    transportModes: [],
    accessDifficulty: null,
    difficulty: null,
    parking: null,
    combinesWith: ["Agios Spiridon / Antinioti / Kalamaki / jezdecká aktivita"],
    warnings: [],
    timeFromHotel: null,
    mapsQuery: "Agios Spiridon Beach, Korfu",
    sources: [],
    sourceException: {
      reason: "SOURCE_PACK uvádí Agios Spiridon Beach jako katalogovou položku v citovaných řádcích; nepřiřazuje mu však konkrétní oficiální ani ověřovací URL, proto nebyl odkaz doplněn odhadem.",
      sp: "SP:78",
    },
    verify: [],
    facts: [],
    sp: "SP:78",
  },
  {
    id: "kalamaki-apraos",
    canonicalName: "Kalamaki / Apraos Beach",
    czName: null,
    category: "plaz",
    subcategory: "mělčí voda, otevřený výhled",
    tier: "doporuceni",
    area: "blizko-zakladny",
    why: "Mělčí voda, otevřený výhled.",
    wow: null,
    userPriority: null,
    visitDuration: null,
    bestPartOfDay: null,
    weather: null,
    weatherFit: [],
    transport: [],
    transportModes: [],
    accessDifficulty: null,
    difficulty: null,
    parking: null,
    combinesWith: ["Agios Spiridon / Antinioti / Kalamaki / jezdecká aktivita"],
    warnings: [],
    timeFromHotel: null,
    mapsQuery: "Kalamaki Beach Apraos, Korfu",
    sources: [],
    sourceException: {
      reason: "SOURCE_PACK uvádí Kalamaki / Apraos Beach jako katalogovou položku v citovaných řádcích; nepřiřazuje mu však konkrétní oficiální ani ověřovací URL, proto nebyl odkaz doplněn odhadem.",
      sp: "SP:79",
    },
    verify: [],
    facts: [],
    sp: "SP:79",
  },
];

/** Pláže severozápad — SP:80–83. Canal d'Amour a Porto Timoni jsou v must-see. */
const BEACH_SEEDS_SEVEROZAPAD: PlaceSeed[] = [
  {
    id: "sidari-beach",
    canonicalName: "Sidari Beach",
    czName: null,
    category: "plaz",
    subcategory: "letovisko, pláž",
    tier: "doporuceni",
    area: "severozapad",
    why: "Severozápadní letovisko; u Canal d'Amour, živá scéna.",
    wow: null,
    userPriority: null,
    visitDuration: null,
    bestPartOfDay: null,
    weather: null,
    weatherFit: [],
    transport: [],
    transportModes: [],
    accessDifficulty: null,
    difficulty: null,
    parking: null,
    combinesWith: ["Sidari / Canal d'Amour / Cape Drastis / Loggas"],
    warnings: [],
    timeFromHotel: null,
    mapsQuery: "Sidari Beach, Korfu",
    sources: [],
    sourceException: {
      reason: "SOURCE_PACK uvádí Sidari Beach jako katalogovou položku v citovaných řádcích; nepřiřazuje mu však konkrétní oficiální ani ověřovací URL, proto nebyl odkaz doplněn odhadem.",
      sp: "SP:80",
    },
    verify: [],
    facts: [],
    sp: "SP:80",
  },
  {
    id: "cape-drastis",
    canonicalName: "Cape Drastis",
    czName: null,
    category: "priroda",
    subcategory: "mys, scenérie, vyhlídky",
    tier: "doporuceni",
    area: "severozapad",
    why: "Scenérie a vyhlídky na krajním severozápadě.",
    wow: null,
    userPriority: null,
    visitDuration: null,
    bestPartOfDay: null,
    weather: null,
    weatherFit: [],
    transport: [],
    transportModes: [],
    accessDifficulty: null,
    difficulty: null,
    parking: null,
    combinesWith: ["Sidari / Canal d'Amour / Cape Drastis / Loggas"],
    warnings: ["Přístup a lodní provoz ověřit. (SP:81)"],
    timeFromHotel: null,
    mapsQuery: "Cape Drastis, Korfu",
    sources: [],
    sourceException: {
      reason: "SOURCE_PACK uvádí Cape Drastis jako katalogovou položku v citovaných řádcích; nepřiřazuje mu však konkrétní oficiální ani ověřovací URL, proto nebyl odkaz doplněn odhadem.",
      sp: "SP:81",
    },
    verify: [
      { what: "Přístup a lodní provoz ověřit.", sp: "SP:81", source: null },
    ],
    facts: [],
    sp: "SP:81",
  },
  {
    id: "loggas-sunset-beach",
    canonicalName: "Loggas / Sunset Beach",
    czName: null,
    category: "plaz",
    subcategory: "západ slunce",
    tier: "doporuceni",
    area: "severozapad",
    why: "Populární pláž pro sledování západu slunce.",
    wow: null,
    userPriority: null,
    visitDuration: null,
    bestPartOfDay: null,
    weather: null,
    weatherFit: [],
    transport: [],
    transportModes: [],
    accessDifficulty: null,
    difficulty: null,
    parking: null,
    combinesWith: ["Sidari / Canal d'Amour / Cape Drastis / Loggas"],
    warnings: [],
    timeFromHotel: null,
    mapsQuery: "Loggas Sunset Beach, Korfu",
    sources: [],
    sourceException: {
      reason: "SOURCE_PACK uvádí Loggas / Sunset Beach jako katalogovou položku v citovaných řádcích; nepřiřazuje mu však konkrétní oficiální ani ověřovací URL, proto nebyl odkaz doplněn odhadem.",
      sp: "SP:81",
    },
    verify: [],
    facts: [],
    sp: "SP:81",
  },
  {
    id: "agios-georgios-pagon",
    canonicalName: "Agios Georgios Pagon",
    czName: null,
    category: "plaz",
    subcategory: "výchozí bod pro Porto Timoni a loď",
    tier: "doporuceni",
    area: "severozapad",
    why: "Výchozí bod k Porto Timoni bez pěšího sestupu, lodní varianta.",
    wow: null,
    userPriority: null,
    visitDuration: null,
    bestPartOfDay: null,
    weather: null,
    weatherFit: [],
    transport: ["Lodí k Porto Timoni."],
    transportModes: ["lod"],
    accessDifficulty: null,
    difficulty: null,
    parking: null,
    combinesWith: ["Afionas / Porto Timoni / Agios Georgios Pagon"],
    warnings: [],
    timeFromHotel: null,
    mapsQuery: "Agios Georgios Pagon, Korfu",
    sources: [],
    sourceException: {
      reason: "SOURCE_PACK uvádí Agios Georgios Pagon jako katalogovou položku v citovaných řádcích; nepřiřazuje mu však konkrétní oficiální ani ověřovací URL, proto nebyl odkaz doplněn odhadem.",
      sp: "SP:82, SP:200",
    },
    verify: [],
    facts: [],
    sp: "SP:82, SP:200",
  },
];

/** Pláže západ — SP:84–88. Paleokastritsa, Rovinia, Agios Gordios, Myrtiotissa jsou v must-see. */
const BEACH_SEEDS_ZAPAD: PlaceSeed[] = [
  {
    id: "liapades",
    canonicalName: "Liapades Beach",
    czName: null,
    category: "plaz",
    subcategory: "pláž, výchozí bod lodí",
    tier: "doporuceni",
    area: "zapad",
    why: "Západ ostrova; výchozí bod pro lodní pronájem.",
    wow: null,
    userPriority: null,
    visitDuration: null,
    bestPartOfDay: null,
    weather: null,
    weatherFit: [],
    transport: [],
    transportModes: [],
    accessDifficulty: null,
    difficulty: null,
    parking: null,
    combinesWith: [
      "Paleokastritsa / Liapades / Rovinia / Angelokastro nebo Lakones",
    ],
    warnings: [],
    timeFromHotel: null,
    mapsQuery: "Liapades Beach, Korfu",
    sources: [],
    sourceException: {
      reason: "SOURCE_PACK uvádí Liapades Beach jako katalogovou položku v citovaných řádcích; nepřiřazuje mu však konkrétní oficiální ani ověřovací URL, proto nebyl odkaz doplněn odhadem.",
      sp: "SP:85, SP:193",
    },
    verify: [],
    facts: [],
    sp: "SP:85, SP:193",
  },
  {
    id: "stelari",
    canonicalName: "Stelari Beach",
    czName: null,
    category: "plaz",
    subcategory: "zejména lodí",
    tier: "dalsi-moznost",
    area: "zapad",
    why: "Přístupná zejména lodí.",
    wow: null,
    userPriority: null,
    visitDuration: null,
    bestPartOfDay: null,
    weather: null,
    weatherFit: ["citlive-na-vitr"],
    transport: ["Zejména lodí."],
    transportModes: ["lod"],
    accessDifficulty: null,
    difficulty: null,
    parking: null,
    combinesWith: [
      "Paleokastritsa / Liapades / Rovinia / Angelokastro nebo Lakones",
    ],
    warnings: [],
    timeFromHotel: null,
    mapsQuery: "Stelari Beach, Korfu",
    sources: [],
    sourceException: {
      reason: "SOURCE_PACK uvádí Stelari Beach jako katalogovou položku v citovaných řádcích; nepřiřazuje mu však konkrétní oficiální ani ověřovací URL, proto nebyl odkaz doplněn odhadem.",
      sp: "SP:85",
    },
    verify: [],
    facts: [],
    sp: "SP:85",
  },
  {
    id: "mikro-stelari",
    canonicalName: "Mikro Stelari Beach",
    czName: null,
    category: "plaz",
    subcategory: "zejména lodí",
    tier: "dalsi-moznost",
    area: "zapad",
    why: "Malá skrytá pláž, přístupná zejména lodí.",
    wow: null,
    userPriority: null,
    visitDuration: null,
    bestPartOfDay: null,
    weather: null,
    weatherFit: ["citlive-na-vitr"],
    transport: ["Zejména lodí."],
    transportModes: ["lod"],
    accessDifficulty: null,
    difficulty: null,
    parking: null,
    combinesWith: [],
    warnings: [],
    timeFromHotel: null,
    mapsQuery: "Mikro Stelari Beach, Korfu",
    sources: [],
    sourceException: {
      reason: "SOURCE_PACK uvádí Mikro Stelari Beach jako katalogovou položku v citovaných řádcích; nepřiřazuje mu však konkrétní oficiální ani ověřovací URL, proto nebyl odkaz doplněn odhadem.",
      sp: "SP:85",
    },
    verify: [],
    facts: [],
    sp: "SP:85",
  },
  {
    id: "limni",
    canonicalName: "Limni Beach",
    czName: null,
    category: "plaz",
    subcategory: "dvojitá pláž",
    tier: "dalsi-moznost",
    area: "zapad",
    why: "Dvojitá pláž na západ ostrova.",
    wow: null,
    userPriority: null,
    visitDuration: null,
    bestPartOfDay: null,
    weather: null,
    weatherFit: [],
    transport: [],
    transportModes: [],
    accessDifficulty: null,
    difficulty: null,
    parking: null,
    combinesWith: [],
    warnings: [],
    timeFromHotel: null,
    mapsQuery: "Limni Beach, Korfu",
    sources: [],
    sourceException: {
      reason: "SOURCE_PACK uvádí Limni Beach jako katalogovou položku v citovaných řádcích; nepřiřazuje mu však konkrétní oficiální ani ověřovací URL, proto nebyl odkaz doplněn odhadem.",
      sp: "SP:85",
    },
    verify: [],
    facts: [],
    sp: "SP:85",
  },
  {
    id: "kastelli",
    canonicalName: "Kastelli Beach",
    czName: null,
    category: "plaz",
    subcategory: "zejména lodí",
    tier: "dalsi-moznost",
    area: "zapad",
    why: "Přístupná zejména lodí.",
    wow: null,
    userPriority: null,
    visitDuration: null,
    bestPartOfDay: null,
    weather: null,
    weatherFit: ["citlive-na-vitr"],
    transport: ["Zejména lodí."],
    transportModes: ["lod"],
    accessDifficulty: null,
    difficulty: null,
    parking: null,
    combinesWith: [],
    warnings: [],
    timeFromHotel: null,
    mapsQuery: "Kastelli Beach, Korfu",
    sources: [],
    sourceException: {
      reason: "SOURCE_PACK uvádí Kastelli Beach jako katalogovou položku v citovaných řádcích; nepřiřazuje mu však konkrétní oficiální ani ověřovací URL, proto nebyl odkaz doplněn odhadem.",
      sp: "SP:86",
    },
    verify: [],
    facts: [],
    sp: "SP:86",
  },
  {
    id: "mikro-kastelli",
    canonicalName: "Mikro Kastelli Beach",
    czName: null,
    category: "plaz",
    subcategory: "zejména lodí",
    tier: "dalsi-moznost",
    area: "zapad",
    why: "Malá pláž, přístupná zejména lodí.",
    wow: null,
    userPriority: null,
    visitDuration: null,
    bestPartOfDay: null,
    weather: null,
    weatherFit: ["citlive-na-vitr"],
    transport: ["Zejména lodí."],
    transportModes: ["lod"],
    accessDifficulty: null,
    difficulty: null,
    parking: null,
    combinesWith: [],
    warnings: [],
    timeFromHotel: null,
    mapsQuery: "Mikro Kastelli Beach, Korfu",
    sources: [],
    sourceException: {
      reason: "SOURCE_PACK uvádí Mikro Kastelli Beach jako katalogovou položku v citovaných řádcích; nepřiřazuje mu však konkrétní oficiální ani ověřovací URL, proto nebyl odkaz doplněn odhadem.",
      sp: "SP:86",
    },
    verify: [],
    facts: [],
    sp: "SP:86",
  },
  {
    id: "paradise-chomi",
    canonicalName: "Paradise / Chomi Beach",
    czName: null,
    category: "plaz",
    subcategory: "lodí, omezení pod útesy",
    tier: "dalsi-moznost",
    area: "zapad",
    why: "Pláž dostupná lodí; omezení pod útesy respektovat.",
    wow: null,
    userPriority: null,
    visitDuration: null,
    bestPartOfDay: null,
    weather: null,
    weatherFit: ["citlive-na-vitr"],
    transport: ["Lodí."],
    transportModes: ["lod"],
    accessDifficulty: null,
    difficulty: null,
    parking: null,
    combinesWith: [
      "Paleokastritsa / Liapades / Rovinia / Angelokastro nebo Lakones",
    ],
    warnings: ["Lodí, respektovat omezení pod útesy. (SP:86–87)"],
    timeFromHotel: null,
    mapsQuery: "Paradise Beach Chomi, Korfu",
    sources: [],
    sourceException: {
      reason: "SOURCE_PACK uvádí Paradise / Chomi Beach jako katalogovou položku v citovaných řádcích; nepřiřazuje mu však konkrétní oficiální ani ověřovací URL, proto nebyl odkaz doplněn odhadem.",
      sp: "SP:86–87",
    },
    verify: [],
    facts: [],
    sp: "SP:86–87",
  },
  {
    id: "giali",
    canonicalName: "Giali Beach",
    czName: null,
    category: "plaz",
    subcategory: "jen v povoleném lodním dosahu",
    tier: "dalsi-moznost",
    area: "zapad",
    why: "Jen v povoleném lodním dosahu.",
    wow: null,
    userPriority: null,
    visitDuration: null,
    bestPartOfDay: null,
    weather: null,
    weatherFit: ["citlive-na-vitr"],
    transport: ["Lodí — jen v povoleném dosahu."],
    transportModes: ["lod"],
    accessDifficulty: null,
    difficulty: null,
    parking: null,
    combinesWith: [],
    warnings: ["Jen v povoleném lodním dosahu. (SP:87)"],
    timeFromHotel: null,
    mapsQuery: "Giali Beach, Korfu",
    sources: [],
    sourceException: {
      reason: "SOURCE_PACK uvádí Giali Beach jako katalogovou položku v citovaných řádcích; nepřiřazuje mu však konkrétní oficiální ani ověřovací URL, proto nebyl odkaz doplněn odhadem.",
      sp: "SP:87",
    },
    verify: [],
    facts: [],
    sp: "SP:87",
  },
];

/** Pláže severovýchod — SP:89–91. Kassiopi, Avlaki, Nissaki, Barbati jsou v must-see. */
const BEACH_SEEDS_SEVEROVYCHOD: PlaceSeed[] = [
  {
    id: "kerasia-beach",
    canonicalName: "Kerasia Beach",
    czName: null,
    category: "plaz",
    subcategory: null,
    tier: "doporuceni",
    area: "severovychod",
    why: "Severovýchodní pobřeží; v balíčku s Kassiopi a okolím.",
    wow: null,
    userPriority: null,
    visitDuration: null,
    bestPartOfDay: null,
    weather: null,
    weatherFit: [],
    transport: [],
    transportModes: [],
    accessDifficulty: null,
    difficulty: null,
    parking: null,
    combinesWith: ["Kassiopi / Avlaki / Kerasia / Kouloura / Kalami / Agni"],
    warnings: [],
    timeFromHotel: null,
    mapsQuery: "Kerasia Beach, Korfu",
    sources: [],
    sourceException: {
      reason: "SOURCE_PACK uvádí Kerasia Beach jako katalogovou položku v citovaných řádcích; nepřiřazuje mu však konkrétní oficiální ani ověřovací URL, proto nebyl odkaz doplněn odhadem.",
      sp: "SP:89",
    },
    verify: [],
    facts: [],
    sp: "SP:89",
  },
  {
    id: "kouloura",
    canonicalName: "Kouloura",
    czName: null,
    category: "plaz",
    subcategory: "malý podkovovitý přístav",
    tier: "doporuceni",
    area: "severovychod",
    why: "Malý podkovovitý přístav; krátká zastávka.",
    wow: null,
    userPriority: null,
    visitDuration: null,
    bestPartOfDay: null,
    weather: null,
    weatherFit: [],
    transport: [],
    transportModes: [],
    accessDifficulty: null,
    difficulty: null,
    parking: null,
    combinesWith: ["Kassiopi / Avlaki / Kerasia / Kouloura / Kalami / Agni"],
    warnings: [],
    timeFromHotel: null,
    mapsQuery: "Kouloura, Korfu",
    sources: [],
    sourceException: {
      reason: "SOURCE_PACK uvádí Kouloura jako katalogovou položku v citovaných řádcích; nepřiřazuje mu však konkrétní oficiální ani ověřovací URL, proto nebyl odkaz doplněn odhadem.",
      sp: "SP:90",
    },
    verify: [],
    facts: [],
    sp: "SP:90",
  },
  {
    id: "kalami",
    canonicalName: "Kalami (White House)",
    czName: null,
    category: "plaz",
    subcategory: "zátoka, White House",
    tier: "doporuceni",
    area: "severovychod",
    why: "Zátoka a White House (spojeno s Lawrencem Durrelem).",
    wow: null,
    userPriority: null,
    visitDuration: null,
    bestPartOfDay: null,
    weather: null,
    weatherFit: [],
    transport: [],
    transportModes: [],
    accessDifficulty: null,
    difficulty: null,
    parking: null,
    combinesWith: ["Kassiopi / Avlaki / Kerasia / Kouloura / Kalami / Agni"],
    warnings: [],
    timeFromHotel: null,
    mapsQuery: "Kalami White House, Korfu",
    sources: [],
    sourceException: {
      reason: "SOURCE_PACK uvádí Kalami (White House) jako katalogovou položku v citovaných řádcích; nepřiřazuje mu však konkrétní oficiální ani ověřovací URL, proto nebyl odkaz doplněn odhadem.",
      sp: "SP:90",
    },
    verify: [],
    facts: [],
    sp: "SP:90",
  },
  {
    id: "agni-bay",
    canonicalName: "Agni Bay",
    czName: null,
    category: "plaz",
    subcategory: "pláž a taverny u vody",
    tier: "doporuceni",
    area: "severovychod",
    why: "Pláž a taverny přímo u vody.",
    wow: null,
    userPriority: null,
    visitDuration: null,
    bestPartOfDay: null,
    weather: null,
    weatherFit: [],
    transport: [],
    transportModes: [],
    accessDifficulty: null,
    difficulty: null,
    parking: null,
    combinesWith: ["Kassiopi / Avlaki / Kerasia / Kouloura / Kalami / Agni"],
    warnings: [],
    timeFromHotel: null,
    mapsQuery: "Agni Bay, Korfu",
    sources: [],
    sourceException: {
      reason: "SOURCE_PACK uvádí Agni Bay jako katalogovou položku v citovaných řádcích; nepřiřazuje mu však konkrétní oficiální ani ověřovací URL, proto nebyl odkaz doplněn odhadem.",
      sp: "SP:90",
    },
    verify: [],
    facts: [],
    sp: "SP:90",
  },
  {
    id: "kaminaki",
    canonicalName: "Kaminaki Beach",
    czName: null,
    category: "plaz",
    subcategory: null,
    tier: "doporuceni",
    area: "severovychod",
    why: "Severovýchodní pobřeží, v linii Nissaki – Kaminaki – Barbati.",
    wow: null,
    userPriority: null,
    visitDuration: null,
    bestPartOfDay: null,
    weather: null,
    weatherFit: [],
    transport: [],
    transportModes: [],
    accessDifficulty: null,
    difficulty: null,
    parking: null,
    combinesWith: ["Nissaki / Kaminaki / Barbati / Ipsos"],
    warnings: [],
    timeFromHotel: null,
    mapsQuery: "Kaminaki Beach, Korfu",
    sources: [],
    sourceException: {
      reason: "SOURCE_PACK uvádí Kaminaki Beach jako katalogovou položku v citovaných řádcích; nepřiřazuje mu však konkrétní oficiální ani ověřovací URL, proto nebyl odkaz doplněn odhadem.",
      sp: "SP:91",
    },
    verify: [],
    facts: [],
    sp: "SP:91",
  },
  {
    id: "ipsos",
    canonicalName: "Ipsos Beach",
    czName: null,
    category: "plaz",
    subcategory: "pláž, výchozí bod pro vodní aktivity",
    tier: "dalsi-moznost",
    area: "severovychod",
    why: "Pláž a výchozí bod k vodním aktivitám. Lodní varianta na jeskyně a zátoky.",
    wow: null,
    userPriority: null,
    visitDuration: null,
    bestPartOfDay: null,
    weather: null,
    weatherFit: [],
    transport: [],
    transportModes: [],
    accessDifficulty: null,
    difficulty: null,
    parking: null,
    combinesWith: ["Nissaki / Kaminaki / Barbati / Ipsos"],
    warnings: [],
    timeFromHotel: null,
    mapsQuery: "Ipsos Beach, Korfu",
    sources: [],
    sourceException: {
      reason: "SOURCE_PACK uvádí Ipsos Beach jako katalogovou položku v citovaných řádcích; nepřiřazuje mu však konkrétní oficiální ani ověřovací URL, proto nebyl odkaz doplněn odhadem.",
      sp: "SP:91, SP:210",
    },
    verify: [],
    facts: [],
    sp: "SP:91, SP:210",
  },
];

/** Pláže jih a jihozápad — SP:92–94. Chalikounas, Issos, Marathias jsou v must-see. */
const BEACH_SEEDS_JIH: PlaceSeed[] = [
  {
    id: "lake-korission",
    canonicalName: "Lake Korission",
    czName: "Jezero Korission",
    category: "priroda",
    subcategory: "přírodní spojnice, laguna",
    tier: "doporuceni",
    area: "jih-jihozapad",
    why: "Přírodní laguna, spojnice mezi Chalikounas a Issos.",
    wow: null,
    userPriority: null,
    visitDuration: null,
    bestPartOfDay: null,
    weather: null,
    weatherFit: [],
    transport: [],
    transportModes: [],
    accessDifficulty: null,
    difficulty: null,
    parking: null,
    combinesWith: ["Chalikounas / Lake Korission / Issos"],
    warnings: [],
    timeFromHotel: null,
    mapsQuery: "Lake Korission, Korfu",
    sources: [],
    sourceException: {
      reason: "SOURCE_PACK uvádí Lake Korission jako katalogovou položku v citovaných řádcích; nepřiřazuje mu však konkrétní oficiální ani ověřovací URL, proto nebyl odkaz doplněn odhadem.",
      sp: "SP:93",
    },
    verify: [],
    facts: [],
    sp: "SP:93",
  },
  {
    id: "boukari",
    canonicalName: "Boukari Beach",
    czName: null,
    category: "plaz",
    subcategory: "klidné pobřeží, rybí taverny",
    tier: "dalsi-moznost",
    area: "jih-jihozapad",
    why: "Klidnější pobřeží, rybí taverny.",
    wow: null,
    userPriority: null,
    visitDuration: null,
    bestPartOfDay: null,
    weather: null,
    weatherFit: [],
    transport: [],
    transportModes: [],
    accessDifficulty: null,
    difficulty: null,
    parking: null,
    combinesWith: ["Marathias / Boukari / Petriti"],
    warnings: [],
    timeFromHotel: null,
    mapsQuery: "Boukari Beach, Korfu",
    sources: [],
    sourceException: {
      reason: "SOURCE_PACK uvádí Boukari Beach jako katalogovou položku v citovaných řádcích; nepřiřazuje mu však konkrétní oficiální ani ověřovací URL, proto nebyl odkaz doplněn odhadem.",
      sp: "SP:94",
    },
    verify: [],
    facts: [],
    sp: "SP:94",
  },
  {
    id: "petriti",
    canonicalName: "Petriti Beach",
    czName: null,
    category: "plaz",
    subcategory: "klidné pobřeží, rybí taverny",
    tier: "dalsi-moznost",
    area: "jih-jihozapad",
    why: "Klidnější pobřeží, rybí taverny.",
    wow: null,
    userPriority: null,
    visitDuration: null,
    bestPartOfDay: null,
    weather: null,
    weatherFit: [],
    transport: [],
    transportModes: [],
    accessDifficulty: null,
    difficulty: null,
    parking: null,
    combinesWith: ["Marathias / Boukari / Petriti"],
    warnings: [],
    timeFromHotel: null,
    mapsQuery: "Petriti Beach, Korfu",
    sources: [],
    sourceException: {
      reason: "SOURCE_PACK uvádí Petriti Beach jako katalogovou položku v citovaných řádcích; nepřiřazuje mu však konkrétní oficiální ani ověřovací URL, proto nebyl odkaz doplněn odhadem.",
      sp: "SP:94",
    },
    verify: [],
    facts: [],
    sp: "SP:94",
  },
  {
    id: "benitses",
    canonicalName: "Benitses / jihovýchod",
    czName: null,
    category: "plaz",
    subcategory: "doplňková oblast",
    tier: "dalsi-moznost",
    area: "jih-jihozapad",
    why: "Doplňková oblast, klidnější pobřeží nebo lodní varianta.",
    wow: null,
    userPriority: null,
    visitDuration: null,
    bestPartOfDay: null,
    weather: null,
    weatherFit: [],
    transport: [],
    transportModes: [],
    accessDifficulty: null,
    difficulty: null,
    parking: null,
    combinesWith: [],
    warnings: [],
    timeFromHotel: null,
    mapsQuery: "Benitses, Korfu",
    sources: [],
    sourceException: {
      reason: "SOURCE_PACK uvádí Benitses / jihovýchod jako katalogovou položku v citovaných řádcích; nepřiřazuje mu však konkrétní oficiální ani ověřovací URL, proto nebyl odkaz doplněn odhadem.",
      sp: "SP:94",
    },
    verify: [],
    facts: [],
    sp: "SP:94",
  },
];

// ─── Památky, města, vesnice, příroda, vyhlídky (část 8, SP:96–111) ───────────

const HERITAGE_SEEDS: PlaceSeed[] = [
  {
    id: "corfu-town",
    canonicalName: "Corfu Town",
    czName: "Město Korfu (Kerkyra)",
    category: "mesto",
    subcategory: "stará pevnost, Spianada, Liston, gastronomie",
    tier: "doporuceni",
    area: "corfu-town",
    why: "Stará pevnost, Spianada, Liston, kostel sv. Spyridona, staré město, promenáda, gastronomie, večerní kultura.",
    wow: null,
    userPriority: null,
    visitDuration: null,
    bestPartOfDay: null,
    weather: "Dobrá možnost při horším počasí.",
    weatherFit: ["vhodne-pri-horsim-pocasi"],
    transport: ["Autobusem — Green Bus A3.", "Taxíkem."],
    transportModes: ["bus", "taxi"],
    accessDifficulty: null,
    difficulty: null,
    parking: null,
    combinesWith: ["Corfu Town / festival / pevnost / večerní gastronomie"],
    warnings: [],
    timeFromHotel: null,
    mapsQuery: "Corfu Town, Kerkyra, Greece",
    sources: [],
    sourceException: {
      reason: "SOURCE_PACK uvádí Corfu Town jako katalogovou položku v citovaných řádcích; nepřiřazuje mu však konkrétní oficiální ani ověřovací URL, proto nebyl odkaz doplněn odhadem.",
      sp: "SP:97–98, SP:354–355",
    },
    verify: [],
    facts: [],
    sp: "SP:97–98, SP:354–355",
  },
  {
    id: "kassiopi",
    canonicalName: "Kassiopi (vesnice)",
    czName: null,
    category: "vesnice",
    subcategory: "přístav, hrad, restaurace",
    tier: "doporuceni",
    area: "severovychod",
    why: "Přístav, hrad, restaurace a blízké pláže (Bataria, Kanoni, Avlaki).",
    wow: null,
    userPriority: null,
    visitDuration: null,
    bestPartOfDay: null,
    weather: null,
    weatherFit: [],
    transport: [],
    transportModes: [],
    accessDifficulty: null,
    difficulty: null,
    parking: null,
    combinesWith: ["Kassiopi / Avlaki / Kerasia / Kouloura / Kalami / Agni"],
    warnings: [],
    timeFromHotel: null,
    mapsQuery: "Kassiopi village, Korfu",
    sources: [],
    sourceException: {
      reason: "SOURCE_PACK uvádí Kassiopi (vesnice) jako katalogovou položku v citovaných řádcích; nepřiřazuje mu však konkrétní oficiální ani ověřovací URL, proto nebyl odkaz doplněn odhadem.",
      sp: "SP:98",
    },
    verify: [],
    facts: [],
    sp: "SP:98",
  },
  {
    id: "old-perithia",
    canonicalName: "Old Perithia",
    czName: "Stará Perithia",
    category: "vesnice",
    subcategory: "historická kamenná vesnice, kostely, taverny",
    tier: "doporuceni",
    area: "vnitrozemi",
    why: "Historická kamenná vesnice s kostely a tavarnami ve vnitrozemí.",
    wow: null,
    userPriority: null,
    visitDuration: null,
    bestPartOfDay: null,
    weather: null,
    weatherFit: [],
    transport: ["Autem."],
    transportModes: ["auto"],
    accessDifficulty: null,
    difficulty: null,
    parking: null,
    combinesWith: ["Old Perithia / Pantokrator / Agios Spiridon nebo Kalamaki"],
    warnings: ["Na Pantokrator a do Old Perithie jet za světla."],
    timeFromHotel: null,
    mapsQuery: "Old Perithia, Korfu",
    sources: [],
    sourceException: {
      reason: "SOURCE_PACK uvádí Old Perithia jako katalogovou položku v citovaných řádcích; nepřiřazuje mu však konkrétní oficiální ani ověřovací URL, proto nebyl odkaz doplněn odhadem.",
      sp: "SP:99",
    },
    verify: [],
    facts: [],
    sp: "SP:99",
  },
  {
    id: "mount-pantokrator",
    canonicalName: "Mount Pantokrator",
    czName: null,
    category: "vyhlidka",
    subcategory: "nejvyšší bod, klášter, panorama",
    tier: "doporuceni",
    area: "vnitrozemi",
    why: "Nejvyšší bod Korfu, klášter, výhledy. Pouze za dobré viditelnosti.",
    wow: null,
    userPriority: null,
    visitDuration: null,
    bestPartOfDay: null,
    weather: "Jen za dobré viditelnosti.",
    weatherFit: ["dobra-viditelnost"],
    transport: ["Autem."],
    transportModes: ["auto"],
    accessDifficulty: null,
    difficulty: null,
    parking: null,
    combinesWith: ["Old Perithia / Pantokrator / Agios Spiridon nebo Kalamaki"],
    warnings: [
      "Jen za dobré viditelnosti. (SP:99–100)",
      "Na Pantokrator jet za světla.",
    ],
    timeFromHotel: null,
    mapsQuery: "Mount Pantokrator, Korfu",
    sources: [],
    sourceException: {
      reason: "SOURCE_PACK uvádí Mount Pantokrator jako katalogovou položku v citovaných řádcích; nepřiřazuje mu však konkrétní oficiální ani ověřovací URL, proto nebyl odkaz doplněn odhadem.",
      sp: "SP:99–100, SP:352–353",
    },
    verify: [],
    facts: [],
    sp: "SP:99–100, SP:352–353",
  },
  {
    id: "afionas",
    canonicalName: "Afionas",
    czName: null,
    category: "vesnice",
    subcategory: "vesnice a vyhlídka nad Porto Timoni",
    tier: "doporuceni",
    area: "severozapad",
    why: "Vesnice a vyhlídka nad Porto Timoni.",
    wow: null,
    userPriority: null,
    visitDuration: null,
    bestPartOfDay: null,
    weather: null,
    weatherFit: [],
    transport: [],
    transportModes: [],
    accessDifficulty: null,
    difficulty: null,
    parking: null,
    combinesWith: ["Afionas / Porto Timoni / Agios Georgios Pagon"],
    warnings: [],
    timeFromHotel: null,
    mapsQuery: "Afionas, Korfu",
    sources: [],
    sourceException: {
      reason: "SOURCE_PACK uvádí Afionas jako katalogovou položku v citovaných řádcích; nepřiřazuje mu však konkrétní oficiální ani ověřovací URL, proto nebyl odkaz doplněn odhadem.",
      sp: "SP:100",
    },
    verify: [],
    facts: [],
    sp: "SP:100",
  },
  {
    id: "angelokastro",
    canonicalName: "Angelokastro",
    czName: null,
    category: "pamatka",
    subcategory: "hrad a výhledy",
    tier: "doporuceni",
    area: "zapad",
    why: "Byzantský hrad a výhledy; spojitelné s Paleokastritsou.",
    wow: null,
    userPriority: null,
    visitDuration: null,
    bestPartOfDay: null,
    weather: null,
    weatherFit: [],
    transport: [],
    transportModes: [],
    accessDifficulty: null,
    difficulty: null,
    parking: null,
    combinesWith: [
      "Paleokastritsa / Liapades / Rovinia / Angelokastro nebo Lakones",
    ],
    warnings: [],
    timeFromHotel: null,
    mapsQuery: "Angelokastro, Korfu",
    sources: [],
    sourceException: {
      reason: "SOURCE_PACK uvádí Angelokastro jako katalogovou položku v citovaných řádcích; nepřiřazuje mu však konkrétní oficiální ani ověřovací URL, proto nebyl odkaz doplněn odhadem.",
      sp: "SP:101",
    },
    verify: [],
    facts: [],
    sp: "SP:101",
  },
  {
    id: "lakones-viewpoint",
    canonicalName: "Lakones Viewpoint",
    czName: "Vyhlídka Lakones",
    category: "vyhlidka",
    subcategory: "panoramatická alternativa",
    tier: "dalsi-moznost",
    area: "zapad",
    why: "Snazší panoramatická alternativa k Angelokastro.",
    wow: null,
    userPriority: null,
    visitDuration: null,
    bestPartOfDay: null,
    weather: null,
    weatherFit: ["dobra-viditelnost"],
    transport: [],
    transportModes: [],
    accessDifficulty: null,
    difficulty: null,
    parking: null,
    combinesWith: [
      "Paleokastritsa / Liapades / Rovinia / Angelokastro nebo Lakones",
    ],
    warnings: [],
    timeFromHotel: null,
    mapsQuery: "Lakones viewpoint, Korfu",
    sources: [],
    sourceException: {
      reason: "SOURCE_PACK uvádí Lakones Viewpoint jako katalogovou položku v citovaných řádcích; nepřiřazuje mu však konkrétní oficiální ani ověřovací URL, proto nebyl odkaz doplněn odhadem.",
      sp: "SP:101–102",
    },
    verify: [],
    facts: [],
    sp: "SP:101–102",
  },
  {
    id: "pelekas-kaisers-throne",
    canonicalName: "Pelekas / Kaiser's Throne",
    czName: null,
    category: "vyhlidka",
    subcategory: "volitelné panorama",
    tier: "dalsi-moznost",
    area: "zapad",
    why: "Volitelné panorama ze skalní plošiny nad Pelekasem.",
    wow: null,
    userPriority: null,
    visitDuration: null,
    bestPartOfDay: null,
    weather: null,
    weatherFit: ["dobra-viditelnost"],
    transport: [],
    transportModes: [],
    accessDifficulty: null,
    difficulty: null,
    parking: null,
    combinesWith: ["Myrtiotissa / Pelekas / Agios Gordios"],
    warnings: [],
    timeFromHotel: null,
    mapsQuery: "Pelekas Kaiser's Throne, Korfu",
    sources: [],
    sourceException: {
      reason: "SOURCE_PACK uvádí Pelekas / Kaiser's Throne jako katalogovou položku v citovaných řádcích; nepřiřazuje mu však konkrétní oficiální ani ověřovací URL, proto nebyl odkaz doplněn odhadem.",
      sp: "SP:102–103",
    },
    verify: [],
    facts: [],
    sp: "SP:102–103",
  },
  {
    id: "antinioti-lagoon",
    canonicalName: "Antinioti Lagoon",
    czName: "Laguna Antinioti",
    category: "priroda",
    subcategory: "chráněné území",
    tier: "doporuceni",
    area: "blizko-zakladny",
    why: "Chráněné území u Agios Spiridon. Součást jezdeckých tras.",
    wow: null,
    userPriority: null,
    visitDuration: null,
    bestPartOfDay: null,
    weather: null,
    weatherFit: [],
    transport: [],
    transportModes: [],
    accessDifficulty: null,
    difficulty: null,
    parking: null,
    combinesWith: ["Agios Spiridon / Antinioti / Kalamaki / jezdecká aktivita"],
    warnings: [],
    timeFromHotel: null,
    mapsQuery: "Antinioti Lagoon, Korfu",
    sources: [],
    sourceException: {
      reason: "SOURCE_PACK uvádí Antinioti Lagoon jako katalogovou položku v citovaných řádcích; nepřiřazuje mu však konkrétní oficiální ani ověřovací URL, proto nebyl odkaz doplněn odhadem.",
      sp: "SP:103",
    },
    verify: [],
    facts: [],
    sp: "SP:103",
  },
  {
    id: "cape-ekaterini",
    canonicalName: "Cape Ekaterini",
    czName: null,
    category: "priroda",
    subcategory: "severní mys",
    tier: "dalsi-moznost",
    area: "blizko-zakladny",
    why: "Severní mys ostrova. Dostupný z delších jezdeckých tras.",
    wow: null,
    userPriority: null,
    visitDuration: null,
    bestPartOfDay: null,
    weather: null,
    weatherFit: [],
    transport: [],
    transportModes: [],
    accessDifficulty: null,
    difficulty: null,
    parking: null,
    combinesWith: [],
    warnings: [],
    timeFromHotel: null,
    mapsQuery: "Cape Ekaterini, Korfu",
    sources: [],
    sourceException: {
      reason: "SOURCE_PACK uvádí Cape Ekaterini jako katalogovou položku v citovaných řádcích; nepřiřazuje mu však konkrétní oficiální ani ověřovací URL, proto nebyl odkaz doplněn odhadem.",
      sp: "SP:104",
    },
    verify: [],
    facts: [],
    sp: "SP:104",
  },
  {
    id: "erimitis",
    canonicalName: "Erimitis",
    czName: null,
    category: "priroda",
    subcategory: "přírodnější pobřeží, malé zátoky",
    tier: "dalsi-moznost",
    area: "severovychod",
    why: "Přírodnější SV pobřeží a malé zátoky.",
    wow: null,
    userPriority: null,
    visitDuration: null,
    bestPartOfDay: null,
    weather: null,
    weatherFit: [],
    transport: [],
    transportModes: [],
    accessDifficulty: null,
    difficulty: null,
    parking: null,
    combinesWith: [],
    warnings: [],
    timeFromHotel: null,
    mapsQuery: "Erimitis, Korfu",
    sources: [],
    sourceException: {
      reason: "SOURCE_PACK uvádí Erimitis jako katalogovou položku v citovaných řádcích; nepřiřazuje mu však konkrétní oficiální ani ověřovací URL, proto nebyl odkaz doplněn odhadem.",
      sp: "SP:104–105",
    },
    verify: [],
    facts: [],
    sp: "SP:104–105",
  },
  {
    id: "paleokastritsa-monastery",
    canonicalName: "Paleokastritsa Monastery",
    czName: "Klášter Paleokastritsa",
    category: "pamatka",
    subcategory: "klášter",
    tier: "doporuceni",
    area: "zapad",
    why: "Klášter nad zátokami Paleokastritsy.",
    wow: null,
    userPriority: null,
    visitDuration: null,
    bestPartOfDay: null,
    weather: null,
    weatherFit: [],
    transport: [],
    transportModes: [],
    accessDifficulty: null,
    difficulty: null,
    parking: null,
    combinesWith: [
      "Paleokastritsa / Liapades / Rovinia / Angelokastro nebo Lakones",
    ],
    warnings: [],
    timeFromHotel: null,
    mapsQuery: "Paleokastritsa Monastery, Korfu",
    sources: [],
    sourceException: {
      reason: "SOURCE_PACK uvádí Paleokastritsa Monastery jako katalogovou položku v citovaných řádcích; nepřiřazuje mu však konkrétní oficiální ani ověřovací URL, proto nebyl odkaz doplněn odhadem.",
      sp: "SP:105",
    },
    verify: [],
    facts: [],
    sp: "SP:105",
  },
  {
    id: "agios-ioannis-sidari",
    canonicalName: "Agios Ioannis Monastery u Sidari",
    czName: null,
    category: "pamatka",
    subcategory: "klášter, svátek 14. 9.",
    tier: "dalsi-moznost",
    area: "severozapad",
    why: "Klášter v oblasti Sidari. Svátek Povýšení sv. Kříže 14. 9.",
    wow: null,
    userPriority: null,
    visitDuration: null,
    bestPartOfDay: null,
    weather: null,
    weatherFit: [],
    transport: [],
    transportModes: [],
    accessDifficulty: null,
    difficulty: null,
    parking: null,
    combinesWith: ["Sidari / Canal d'Amour / Cape Drastis / Loggas"],
    warnings: [],
    timeFromHotel: null,
    mapsQuery: "Agios Ioannis Monastery Sidari, Korfu",
    sources: [],
    sourceException: {
      reason: "SOURCE_PACK uvádí Agios Ioannis Monastery u Sidari jako katalogovou položku v citovaných řádcích; nepřiřazuje mu však konkrétní oficiální ani ověřovací URL, proto nebyl odkaz doplněn odhadem.",
      sp: "SP:105, SP:327–328",
    },
    verify: [
      {
        what: "Aktuální průběh a dostupnost slavnosti ověřit.",
        sp: "SP:105, SP:327–328",
        source: null,
      },
    ],
    facts: [],
    sp: "SP:105, SP:327–328",
  },
  {
    id: "apollon-chram-roda",
    canonicalName: "Pozůstatky Apollónova chrámu v Rodě",
    czName: null,
    category: "pamatka",
    subcategory: "archeologický bod, dórský chrám 5. stol. př. n. l.",
    tier: "doporuceni",
    area: "blizko-zakladny",
    why: "Základy dórského chrámu z 5. stol. př. n. l. západně od Rody. Nenápadný archeologický bod, ne monumentální ruina.",
    wow: null,
    userPriority: null,
    visitDuration: null,
    bestPartOfDay: null,
    weather: null,
    weatherFit: [],
    transport: ["Pěšky z centra Rody."],
    transportModes: ["pesky"],
    accessDifficulty: null,
    difficulty: null,
    parking: null,
    combinesWith: [
      "Roda / Apollónův chrám / Roda Loop nebo pobřežní procházka / Acharavi / Almyros",
    ],
    warnings: [],
    timeFromHotel: null,
    mapsQuery: "Temple of Apollo, Roda, Korfu",
    sources: [],
    sourceException: {
      reason: "SOURCE_PACK uvádí Pozůstatky Apollónova chrámu v Rodě jako katalogovou položku v citovaných řádcích; nepřiřazuje mu však konkrétní oficiální ani ověřovací URL, proto nebyl odkaz doplněn odhadem.",
      sp: "SP:106–108",
    },
    verify: [
      {
        what: "Vstup a přesnou polohu mapového bodu ověřit na místě.",
        sp: "SP:106–108",
        source: null,
      },
    ],
    facts: [],
    sp: "SP:106–108",
  },
  {
    id: "roda-loop",
    canonicalName: "Roda Loop / Sfakera",
    czName: null,
    category: "aktivita",
    subcategory: "pěší okruh",
    tier: "dalsi-moznost",
    area: "blizko-zakladny",
    why: "Lehký okruh cca 5,5 km / 1 h 20 min. Orientační trasa, ověřit průchodnost.",
    wow: null,
    userPriority: null,
    visitDuration: "cca 1 h 20 min",
    bestPartOfDay: null,
    weather: null,
    weatherFit: [],
    transport: ["Pěšky."],
    transportModes: ["pesky"],
    accessDifficulty: "Lehký okruh.",
    difficulty: "snadny",
    parking: null,
    combinesWith: [
      "Roda / Apollónův chrám / Roda Loop nebo pobřežní procházka / Acharavi / Almyros",
    ],
    warnings: [],
    timeFromHotel: null,
    mapsQuery: "Roda Loop, Sfakera, Korfu",
    sources: [],
    sourceException: {
      reason: "SOURCE_PACK uvádí Roda Loop / Sfakera jako katalogovou položku v citovaných řádcích; nepřiřazuje mu však konkrétní oficiální ani ověřovací URL, proto nebyl odkaz doplněn odhadem.",
      sp: "SP:109",
    },
    verify: [
      { what: "Průchodnost okruhu ověřit.", sp: "SP:109", source: null },
    ],
    facts: [],
    sp: "SP:109",
  },
  {
    id: "roda-acharavi-walk",
    canonicalName: "Pobřežní procházka Roda–Acharavi",
    czName: null,
    category: "aktivita",
    subcategory: "pobřežní procházka",
    tier: "dalsi-moznost",
    area: "blizko-zakladny",
    why: "Snadná pobřežní procházka mezi Rodou a Acharavi.",
    wow: null,
    userPriority: null,
    visitDuration: null,
    bestPartOfDay: null,
    weather: null,
    weatherFit: [],
    transport: ["Pěšky."],
    transportModes: ["pesky"],
    accessDifficulty: null,
    difficulty: "snadny",
    parking: null,
    combinesWith: [
      "Roda / Apollónův chrám / Roda Loop nebo pobřežní procházka / Acharavi / Almyros",
    ],
    warnings: [
      "Na úsecích bez chodníku a za tmy reflexní prvky a opatrnost. (SP:110–111)",
    ],
    timeFromHotel: null,
    mapsQuery: "Acharavi Beach, Korfu",
    sources: [],
    sourceException: {
      reason: "SOURCE_PACK uvádí Pobřežní procházka Roda–Acharavi jako katalogovou položku v citovaných řádcích; nepřiřazuje mu však konkrétní oficiální ani ověřovací URL, proto nebyl odkaz doplněn odhadem.",
      sp: "SP:110–111",
    },
    verify: [],
    facts: [],
    sp: "SP:110–111",
  },
];

// ─── Aktivity H1 — katalog „Další možnosti" (SP:231–240) ──────────────────────

const ACTIVITY_SEEDS: PlaceSeed[] = [
  {
    id: "snorkelovani",
    canonicalName: "Šnorchlování",
    czName: null,
    category: "aktivita",
    subcategory: "vodní aktivita",
    tier: "dalsi-moznost",
    area: "neurceno",
    why: "Vodní aktivita, dostupná u různých pláží.",
    wow: null,
    userPriority: null,
    visitDuration: null,
    bestPartOfDay: null,
    weather: null,
    weatherFit: ["citlive-na-vitr"],
    transport: [],
    transportModes: [],
    accessDifficulty: null,
    difficulty: null,
    parking: null,
    combinesWith: [],
    warnings: [],
    timeFromHotel: null,
    mapsQuery: "Snorkeling, Korfu",
    sources: [],
    sourceException: {
      reason: "SOURCE_PACK uvádí Šnorchlování jako katalogovou položku v citovaných řádcích; nepřiřazuje mu však konkrétní oficiální ani ověřovací URL, proto nebyl odkaz doplněn odhadem.",
      sp: "SP:232",
    },
    verify: [
      {
        what: "Dostupnost a místa ověřit aktuálně.",
        sp: "SP:232",
        source: null,
      },
    ],
    facts: [],
    sp: "SP:232",
  },
  {
    id: "sup-sea-kayaking",
    canonicalName: "SUP a sea kayaking",
    czName: null,
    category: "aktivita",
    subcategory: "vodní aktivita",
    tier: "dalsi-moznost",
    area: "neurceno",
    why: "SUP a sea kayaking na klidném moři.",
    wow: null,
    userPriority: null,
    visitDuration: null,
    bestPartOfDay: null,
    weather: null,
    weatherFit: ["citlive-na-vitr"],
    transport: [],
    transportModes: [],
    accessDifficulty: null,
    difficulty: null,
    parking: null,
    combinesWith: [],
    warnings: [],
    timeFromHotel: null,
    mapsQuery: "SUP kayaking, Korfu",
    sources: [
      {
        label: "roda-beach.com — water sports",
        url: "https://roda-beach.com/en/water-sports/",
      },
    ],
    verify: [
      {
        what: "Dostupnost a provoz ověřit aktuálně.",
        sp: "SP:232",
        source: {
          label: "roda-beach.com — water sports",
          url: "https://roda-beach.com/en/water-sports/",
        },
      },
    ],
    facts: [],
    sp: "SP:232, SP:243",
  },
  {
    id: "potapeni",
    canonicalName: "Potápění",
    czName: null,
    category: "aktivita",
    subcategory: "vodní aktivita",
    tier: "dalsi-moznost",
    area: "neurceno",
    why: "Organizované potápění s instruktorem — Dive Easy Acharavi (nejbližší), Apollo Corfu Diving (Nissaki).",
    wow: null,
    userPriority: null,
    visitDuration: null,
    bestPartOfDay: null,
    weather: null,
    weatherFit: ["citlive-na-vitr"],
    transport: [],
    transportModes: [],
    accessDifficulty: null,
    difficulty: null,
    parking: null,
    combinesWith: [],
    warnings: [],
    timeFromHotel: null,
    mapsQuery: "Diving Acharavi, Korfu",
    sources: [
      { label: "divecorfu.com", url: "https://divecorfu.com" },
      { label: "corfudive.com", url: "https://corfudive.com/contact-us/" },
    ],
    verify: [
      {
        what: "Cenu, transfer a dostupnost ověřit přímo u provozovatele.",
        sp: "SP:232, SP:250–257",
        source: { label: "divecorfu.com", url: "https://divecorfu.com" },
      },
    ],
    facts: [],
    sp: "SP:232, SP:250–257",
  },
  {
    id: "cliff-jumping",
    canonicalName: "Cliff jumping / coasteering",
    czName: null,
    category: "aktivita",
    subcategory: "vodní dobrodružství",
    tier: "dalsi-moznost",
    area: "neurceno",
    why: "Pouze s kvalifikovaným průvodcem.",
    wow: null,
    userPriority: null,
    visitDuration: null,
    bestPartOfDay: null,
    weather: null,
    weatherFit: [],
    transport: [],
    transportModes: [],
    accessDifficulty: null,
    difficulty: "narocny",
    parking: null,
    combinesWith: [],
    warnings: ["Pouze s kvalifikovaným průvodcem. (SP:233)"],
    timeFromHotel: null,
    mapsQuery: "Coasteering, Korfu",
    sources: [
      {
        label: "corfuextremesports.com",
        url: "https://corfuextremesports.com",
      },
    ],
    verify: [
      {
        what: "Dostupnost a provozovatel ověřit aktuálně.",
        sp: "SP:233",
        source: null,
      },
    ],
    facts: [],
    sp: "SP:233",
  },
  {
    id: "sunset-plavba",
    canonicalName: "Plavba při západu slunce",
    czName: null,
    category: "aktivita",
    subcategory: "lodní aktivita",
    tier: "dalsi-moznost",
    area: "neurceno",
    why: "Organizovaná plavba při západu slunce.",
    wow: null,
    userPriority: null,
    visitDuration: null,
    bestPartOfDay: null,
    weather: null,
    weatherFit: ["citlive-na-vitr"],
    transport: ["Lodí."],
    transportModes: ["lod"],
    accessDifficulty: null,
    difficulty: null,
    parking: null,
    combinesWith: [],
    warnings: [],
    timeFromHotel: null,
    mapsQuery: "Sunset boat cruise, Korfu",
    sources: [],
    sourceException: {
      reason: "SOURCE_PACK uvádí Plavba při západu slunce jako katalogovou položku v citovaných řádcích; nepřiřazuje mu však konkrétní oficiální ani ověřovací URL, proto nebyl odkaz doplněn odhadem.",
      sp: "SP:233",
    },
    verify: [
      {
        what: "Dostupnost a cenu ověřit aktuálně.",
        sp: "SP:233",
        source: null,
      },
    ],
    facts: [],
    sp: "SP:233",
  },
  {
    id: "pesi-tury",
    canonicalName: "Pěší túry a trekking",
    czName: null,
    category: "aktivita",
    subcategory: "turistika",
    tier: "dalsi-moznost",
    area: "neurceno",
    why: "Pěší túry po ostrovním terénu.",
    wow: null,
    userPriority: null,
    visitDuration: null,
    bestPartOfDay: null,
    weather: null,
    weatherFit: [],
    transport: [],
    transportModes: [],
    accessDifficulty: null,
    difficulty: null,
    parking: null,
    combinesWith: [],
    warnings: [],
    timeFromHotel: null,
    mapsQuery: "Hiking, Korfu",
    sources: [
      {
        label: "corfutouristservices.gr — aktivity",
        url: "https://corfutouristservices.gr/activities-in-corfu/",
      },
    ],
    verify: [],
    facts: [],
    sp: "SP:235",
  },
  {
    id: "jeep-safari",
    canonicalName: "Jeep safari / self-drive 4×4 safari",
    czName: null,
    category: "aktivita",
    subcategory: "off-road",
    tier: "dalsi-moznost",
    area: "neurceno",
    why: "Organizované jeep safari nebo self-drive 4×4.",
    wow: null,
    userPriority: null,
    visitDuration: null,
    bestPartOfDay: null,
    weather: null,
    weatherFit: [],
    transport: [],
    transportModes: [],
    accessDifficulty: null,
    difficulty: null,
    parking: null,
    combinesWith: [],
    warnings: [],
    timeFromHotel: null,
    mapsQuery: "Jeep safari, Korfu",
    sources: [
      {
        label: "corfutouristservices.gr — aktivity",
        url: "https://corfutouristservices.gr/activities-in-corfu/",
      },
    ],
    verify: [
      {
        what: "Dostupnost a cenu ověřit aktuálně.",
        sp: "SP:236",
        source: null,
      },
    ],
    facts: [],
    sp: "SP:236",
  },
  {
    id: "korfu-town-prohlidka",
    canonicalName: "Historická pěší prohlídka Corfu Town",
    czName: null,
    category: "aktivita",
    subcategory: "kulturní aktivita",
    tier: "dalsi-moznost",
    area: "corfu-town",
    why: "Organizovaná historická pěší prohlídka nebo food & culture walking tour.",
    wow: null,
    userPriority: null,
    visitDuration: null,
    bestPartOfDay: null,
    weather: "Dobrá možnost při horším počasí.",
    weatherFit: ["vhodne-pri-horsim-pocasi"],
    transport: ["Autobusem nebo taxíkem do Corfu Town."],
    transportModes: ["bus", "taxi"],
    accessDifficulty: null,
    difficulty: null,
    parking: null,
    combinesWith: ["Corfu Town / festival / pevnost / večerní gastronomie"],
    warnings: [],
    timeFromHotel: null,
    mapsQuery: "Corfu Town walking tour",
    sources: [],
    sourceException: {
      reason: "SOURCE_PACK uvádí Historická pěší prohlídka Corfu Town jako katalogovou položku v citovaných řádcích; nepřiřazuje mu však konkrétní oficiální ani ověřovací URL, proto nebyl odkaz doplněn odhadem.",
      sp: "SP:238",
    },
    verify: [
      {
        what: "Dostupnost guided tour ověřit aktuálně.",
        sp: "SP:238",
        source: null,
      },
    ],
    facts: [],
    sp: "SP:238",
  },
  {
    id: "aqualand",
    canonicalName: "Aqualand",
    czName: null,
    category: "aktivita",
    subcategory: "aquapark, záložní zábavní možnost",
    tier: "dalsi-moznost",
    area: "neurceno",
    why: "Záložní zábavní možnost, zejména při horším počasí.",
    wow: null,
    userPriority: null,
    visitDuration: null,
    bestPartOfDay: null,
    weather: null,
    weatherFit: ["vhodne-pri-horsim-pocasi"],
    transport: [],
    transportModes: [],
    accessDifficulty: null,
    difficulty: null,
    parking: null,
    combinesWith: [],
    warnings: [],
    timeFromHotel: null,
    mapsQuery: "Aqualand, Korfu",
    sources: [],
    sourceException: {
      reason: "SOURCE_PACK uvádí Aqualand jako katalogovou položku v citovaných řádcích; nepřiřazuje mu však konkrétní oficiální ani ověřovací URL, proto nebyl odkaz doplněn odhadem.",
      sp: "SP:237",
    },
    verify: [
      {
        what: "Otevírací dobu, cenu a provoz ověřit aktuálně.",
        sp: "SP:237",
        source: null,
      },
    ],
    facts: [],
    sp: "SP:237",
  },
  {
    id: "paxos-antipaxos",
    canonicalName: "Paxos / Antipaxos",
    czName: null,
    category: "lod",
    subcategory: "organizovaná plavba, ostrovy",
    tier: "dalsi-moznost",
    area: "neurceno",
    why: "Blue Caves, koupání u Antipaxosu, Gaios nebo Lakka. POUZE organizovaná loď nebo charter s profesionálním skipperem.",
    wow: null,
    userPriority: null,
    visitDuration: null,
    bestPartOfDay: null,
    weather: null,
    weatherFit: ["citlive-na-vitr"],
    transport: [
      "Organizovaná loď nebo charter se skipperem.",
      "Odjezdy typicky z Corfu Town, Lefkimmi nebo Benitses — NE z Rody.",
    ],
    transportModes: ["lod"],
    accessDifficulty: null,
    difficulty: null,
    parking: null,
    combinesWith: [],
    warnings: [
      "POUZE organizovaná loď nebo charter s profesionálním skipperem — malý bezlicenční člun NENÍ vhodný pro otevřený přejezd. (SP:214–215)",
      "Odjezdy typicky z Corfu Town, Lefkimmi nebo Benitses — NE z Rody. (SP:216)",
      "Ověřit transfer, skutečný čas na místě, počasí a kompletní cenu. (SP:216–217)",
      "Katalogové částky kolem 49 € jsou pouze orientační lead, ne garantovaná cena. (SP:218)",
    ],
    timeFromHotel: null,
    mapsQuery: "Paxos island, Greece",
    sources: [],
    sourceException: {
      reason: "SOURCE_PACK uvádí Paxos / Antipaxos jako katalogovou položku v citovaných řádcích; nepřiřazuje mu však konkrétní oficiální ani ověřovací URL, proto nebyl odkaz doplněn odhadem.",
      sp: "SP:214–218",
    },
    verify: [
      {
        what: "Transfer, odjezd, délku dne, počasí a kompletní cenu ověřit aktuálně.",
        sp: "SP:214–218",
        source: null,
      },
    ],
    facts: [
      {
        label: "Orientační cena organizované plavby Paxos/Antipaxos",
        value: "cca 49 €/os — orientační lead, ne garantovaná cena",
        freshness: "overit-aktualne" as const,
        checkedAt: null,
        source: null,
        note: "Ověřit kompletní cenu včetně transferu z Rody.",
        sp: "SP:218",
      },
    ],
    sp: "SP:214–218",
  },
];

// ─── Kompletní katalog ─────────────────────────────────────────────────────────

const ALL_CATALOG_SEEDS: PlaceSeed[] = [
  ...BEACH_SEEDS_ZAKLADNA,
  ...BEACH_SEEDS_SEVEROZAPAD,
  ...BEACH_SEEDS_ZAPAD,
  ...BEACH_SEEDS_SEVEROVYCHOD,
  ...BEACH_SEEDS_JIH,
  ...HERITAGE_SEEDS,
  ...ACTIVITY_SEEDS,
];

/** 13 ručních must-see z části 6 SOURCE_PACKu, s doplněnými mapovými body. */
export const MUST_SEE: Place[] = MUST_SEE_SEEDS.map(withGeocode);

/** Zbývající katalog (část 7, 8, 12 SOURCE_PACKu), s doplněnými mapovými body kde jsou. */
export const CATALOG: Place[] = ALL_CATALOG_SEEDS.map(withGeocode);

/** Celý katalog = must-see + ostatní. */
export const PLACES: Place[] = [...MUST_SEE, ...CATALOG];
