import { GEOCODED } from './coords.generated';
import type { Place } from './types';

/**
 * Karta bez mapového bodu. Souřadnice se do karty doplňují výhradně z `coords.generated.ts`,
 * tedy z jednorázového geokódování podle SUPERVISOR DIRECTIVE 01 / D01-A
 * (.korfu/SOURCE_PACK.md ř. 487–498). V tomto souboru se souřadnice nikdy nepíšou ručně.
 */
type PlaceSeed = Omit<
  Place,
  'coords' | 'coordsStatus' | 'coordsNote' | 'coordsSource' | 'coordsQuery' | 'coordsCheckedAt'
>;

/**
 * Katalog karet — Korfu 2026.
 *
 * ZDROJ: výhradně .korfu/SOURCE_PACK.md (verze po druhém úplném reauditu, 13. 9. 2026).
 * Každá karta nese v poli `sp` čísla řádků SOURCE_PACKu, ze kterých je doložená.
 * Hodnota, kterou SOURCE_PACK neuvádí, zůstává `null` / prázdné pole (kontrakt bod 16).
 *
 * MAPOVÉ BODY (mezera G1 → vyřešeno direktivou):
 * Části 1–25 SOURCE_PACKu neobsahují ani jednu číselnou souřadnici (ověřeno grepem na
 * `[0-9]{1,2}\.[0-9]{4,}` a na `°` — jediné zásahy jsou teploty v ř. 349).
 * SUPERVISOR DIRECTIVE 01 / D01-A (ř. 487–498) proto povolila jednorázové geokódování přes
 * OpenStreetMap Nominatim. Výsledek je staticky uložený v `coords.generated.ts` a doplňuje se
 * do karet funkcí `withGeocode()` níže. Ručně psané souřadnice jsou v tomto souboru zakázané.
 *
 * PRAVIDLO R-NAV:
 * `mapsQuery` = první varianta názvu z části 6 + `, Korfu`. Je-li bod ověřený, Navigovat míří
 * na souřadnice; u neověřitelného bodu zůstává Google Maps vyhledávání podle názvu
 * (SOURCE_PACK ř. 497).
 *
 * POŘADÍ: přesně podle číslovaného ručního seznamu v části 6 (ř. 56–71).
 */

/** 13 ručních must-see míst — SOURCE_PACK část 6, ř. 55–72. */
const MUST_SEE_SEEDS: PlaceSeed[] = [
  {
    id: 'canal-damour',
    canonicalName: "Canal d'Amour u Sidari",
    czName: null,
    category: 'plaz',
    subcategory: 'pískovcové útvary a kanály',
    tier: 'must-see',
    area: 'severozapad',
    why: 'Ruční seznam, priorita č. 1. Pískovcové útvary a kanály na severozápadním pobřeží u Sidari.',
    wow: null,
    userPriority: 'Očíslovaná priorita č. 1 (ruční seznam)',
    visitDuration: null,
    bestPartOfDay: null,
    weather: null,
    transport: [],
    accessDifficulty: null,
    parking: null,
    combinesWith: ['Sidari / Canal d’Amour / Cape Drastis / Loggas'],
    warnings: ['Za větru a vln opatrnost.'],
    timeFromHotel: null,
    mapsQuery: "Canal d'Amour, Sidari, Korfu",
    sources: [],
    verify: [],
    sp: 'SP:57, SP:80, SP:116, SP:413',
  },
  {
    id: 'porto-timoni',
    canonicalName: 'Porto Timoni',
    czName: null,
    category: 'plaz',
    subcategory: 'dvojitá pláž',
    tier: 'must-see',
    area: 'severozapad',
    why: 'Ruční seznam, priorita č. 2 — dvojitá pláž, v poznámce označena srdcem. Pěší sestup z Afionasu, nebo příjezd lodí.',
    wow: null,
    userPriority: 'Očíslovaná priorita č. 2, „označena srdcem“ (ruční seznam)',
    visitDuration: null,
    bestPartOfDay: null,
    weather: 'Za mokra problematické.',
    transport: [
      'Pěší sestup z Afionasu.',
      'Lodí — z Agios Georgios Pagon i bez pěšího sestupu.',
    ],
    accessDifficulty: 'Strmá kamenitá cesta.',
    parking: null,
    combinesWith: ['Afionas / Porto Timoni / Agios Georgios Pagon'],
    warnings: ['Strmá kamenitá cesta.', 'Za mokra označeno jako problematické.'],
    timeFromHotel: null,
    mapsQuery: 'Porto Timoni, Korfu',
    sources: [],
    verify: [],
    sp: 'SP:58, SP:82–83, SP:117, SP:200, SP:353, SP:414',
  },
  {
    id: 'paleokastritsa',
    canonicalName: 'Paleokastritsa / Palaiokastritsa',
    czName: null,
    category: 'plaz',
    subcategory: 'zátoky, klášter, jeskyně',
    tier: 'must-see',
    area: 'zapad',
    why: 'Ruční seznam, priorita č. 3. Zátoky, klášter, jeskyně, krátké plavby i vlastní loď. Nejdramatičtější scenérie a nejvíc jeskyní a boat-only pláží.',
    wow: null,
    userPriority: 'Očíslovaná priorita č. 3 (ruční seznam)',
    visitDuration: null,
    bestPartOfDay: null,
    weather: null,
    transport: ['Krátké plavby i vlastní loď.'],
    accessDifficulty: null,
    parking: null,
    combinesWith: ['Paleokastritsa / Liapades / Rovinia / Angelokastro nebo Lakones'],
    warnings: [],
    timeFromHotel: null,
    mapsQuery: 'Paleokastritsa, Korfu',
    sources: [],
    verify: [
      {
        what: 'Orientační cena bezlicenční lodi v Paleokastritse: cca od 100 €, často bez paliva — ověřit aktuálně.',
        sp: 'SP:220–221',
        source: null,
      },
    ],
    sp: 'SP:59, SP:84–85, SP:101, SP:118, SP:183–185, SP:221, SP:417',
  },
  {
    id: 'kassiopi-beach',
    canonicalName: 'Kassiopi Beach',
    czName: null,
    category: 'plaz',
    subcategory: 'pláž, přístav a hrad',
    tier: 'must-see',
    area: 'severovychod',
    why: 'Ruční seznam. Kromě pláže i přístav, hrad a restaurace; blízké pláže v okolí.',
    wow: null,
    userPriority: null,
    visitDuration: null,
    bestPartOfDay: null,
    weather: null,
    transport: [],
    accessDifficulty: null,
    parking: null,
    combinesWith: ['Kassiopi / Avlaki / Kerasia / Kouloura / Kalami / Agni'],
    warnings: [],
    timeFromHotel: null,
    mapsQuery: 'Kassiopi, Korfu',
    sources: [],
    verify: [
      {
        what: 'Ověřit, zda „Kassiopi Beach“ nejlépe odpovídá Bataria, Kanoni nebo jiné konkrétní pláži — přesný výběr ověřit.',
        sp: 'SP:61–62, SP:89',
        source: null,
      },
    ],
    sp: 'SP:61–62, SP:89, SP:98, SP:119, SP:416',
  },
  {
    id: 'rovinia-beach',
    canonicalName: 'Rovinia Beach',
    czName: null,
    category: 'plaz',
    subcategory: null,
    tier: 'must-see',
    area: 'zapad',
    why: 'Ruční seznam. Západní pobřeží u Paleokastritsy; dostupná pěšky i z vody.',
    wow: null,
    userPriority: null,
    visitDuration: null,
    bestPartOfDay: null,
    weather: null,
    transport: ['Pěšky i z vody.'],
    accessDifficulty: null,
    parking: null,
    combinesWith: ['Paleokastritsa / Liapades / Rovinia / Angelokastro nebo Lakones'],
    warnings: [],
    timeFromHotel: null,
    mapsQuery: 'Rovinia Beach, Korfu',
    sources: [],
    verify: [],
    sp: 'SP:63, SP:84–85, SP:118, SP:184',
  },
  {
    id: 'agios-gordios',
    canonicalName: 'Agios Gordios',
    czName: null,
    category: 'plaz',
    subcategory: 'pláž, vesnice a panorama',
    tier: 'must-see',
    area: 'zapad',
    why: 'Ruční seznam — vesnice, pláž a panorama. Panoramatické pohledy.',
    wow: null,
    userPriority: null,
    visitDuration: null,
    bestPartOfDay: null,
    weather: null,
    transport: [],
    accessDifficulty: null,
    parking: null,
    combinesWith: ['Myrtiotissa / Pelekas / Agios Gordios'],
    warnings: [],
    timeFromHotel: null,
    mapsQuery: 'Agios Gordios, Korfu',
    sources: [],
    verify: [],
    sp: 'SP:64, SP:88, SP:102, SP:122',
  },
  {
    id: 'issos-beach',
    canonicalName: 'Issos Beach',
    czName: null,
    category: 'plaz',
    subcategory: null,
    tier: 'must-see',
    area: 'jih-jihozapad',
    why: 'Ruční seznam — v poznámce označena hvězdičkou, tedy viditelně silné přání. V katalogu pláží vedena jako výrazná uživatelská priorita.',
    wow: null,
    userPriority: '„Označena hvězdičkou = viditelně silné přání“ (ruční seznam)',
    visitDuration: null,
    bestPartOfDay: null,
    weather: null,
    transport: [],
    accessDifficulty: null,
    parking: null,
    combinesWith: ['Chalikounas / Lake Korission / Issos'],
    warnings: [],
    timeFromHotel: null,
    mapsQuery: 'Issos Beach, Korfu',
    sources: [],
    verify: [],
    sp: 'SP:65, SP:92–93, SP:123',
  },
  {
    id: 'avlaki-beach',
    canonicalName: 'Avlaki Beach',
    czName: null,
    category: 'plaz',
    subcategory: null,
    tier: 'must-see',
    area: 'severovychod',
    why: 'Ruční seznam. Severovýchodní pobřeží v sousedství Kassiopi a Kerasie.',
    wow: null,
    userPriority: null,
    visitDuration: null,
    bestPartOfDay: null,
    weather: null,
    transport: [],
    accessDifficulty: null,
    parking: null,
    combinesWith: ['Kassiopi / Avlaki / Kerasia / Kouloura / Kalami / Agni'],
    warnings: [],
    timeFromHotel: null,
    mapsQuery: 'Avlaki Beach, Korfu',
    sources: [],
    verify: [],
    sp: 'SP:66, SP:89, SP:119, SP:413',
  },
  {
    id: 'marathias-beach',
    canonicalName: 'Marathias Beach',
    czName: null,
    category: 'plaz',
    subcategory: null,
    tier: 'must-see',
    area: 'jih-jihozapad',
    why: 'Ruční seznam. Jih a jihozápad ostrova, v sousedství Issosu a klidnějšího pobřeží u Boukari a Petriti.',
    wow: null,
    userPriority: null,
    visitDuration: null,
    bestPartOfDay: null,
    weather: null,
    transport: [],
    accessDifficulty: null,
    parking: null,
    combinesWith: ['Marathias / Boukari / Petriti'],
    warnings: [],
    timeFromHotel: null,
    mapsQuery: 'Marathias Beach, Korfu',
    sources: [],
    verify: [],
    sp: 'SP:67, SP:92, SP:124',
  },
  {
    id: 'nissaki-beach',
    canonicalName: 'Nissaki Beach',
    czName: null,
    category: 'plaz',
    subcategory: null,
    tier: 'must-see',
    area: 'severovychod',
    why: 'Ruční seznam. Severovýchodní pobřeží s krátkými vzdálenostmi mezi zátokami — Nissaki, Kaminaki, Agni, Kalami, Kouloura, Kerasia.',
    wow: null,
    userPriority: null,
    visitDuration: null,
    bestPartOfDay: null,
    weather: null,
    transport: [],
    accessDifficulty: null,
    parking: null,
    combinesWith: ['Nissaki / Kaminaki / Barbati / Ipsos'],
    warnings: [],
    timeFromHotel: null,
    mapsQuery: 'Nissaki Beach, Korfu',
    sources: [],
    verify: [
      {
        what: 'Orientační cena bezlicenční lodi v Nissaki od 16. 9.: cca 80–170 € podle lodi, často bez paliva — ověřit aktuálně.',
        sp: 'SP:220–223',
        source: null,
      },
    ],
    sp: 'SP:68, SP:91, SP:120, SP:194–198, SP:221–222',
  },
  {
    id: 'chalikounas-beach',
    canonicalName: 'Chalikounas / Halikounas Beach',
    czName: null,
    category: 'plaz',
    subcategory: null,
    tier: 'must-see',
    area: 'jih-jihozapad',
    why: 'Ruční seznam. Jihozápadní pobřeží; Lake Korission je přírodní spojnice mezi Chalikounas a Issos.',
    wow: null,
    userPriority: null,
    visitDuration: null,
    bestPartOfDay: null,
    weather: null,
    transport: [],
    accessDifficulty: null,
    parking: null,
    combinesWith: ['Chalikounas / Lake Korission / Issos'],
    warnings: [],
    timeFromHotel: null,
    mapsQuery: 'Chalikounas Beach, Korfu',
    sources: [],
    verify: [],
    sp: 'SP:69, SP:92–93, SP:123',
  },
  {
    id: 'myrtiotissa-beach',
    canonicalName: 'Myrtiotissa Beach',
    czName: null,
    category: 'plaz',
    subcategory: null,
    tier: 'must-see',
    area: 'zapad',
    why: 'Ruční seznam. Západní pobřeží mezi Paleokastritsou a Agios Gordios.',
    wow: null,
    userPriority: null,
    visitDuration: null,
    bestPartOfDay: null,
    weather: 'Za mokra problematické.',
    transport: [],
    accessDifficulty: null,
    parking: null,
    combinesWith: ['Myrtiotissa / Pelekas / Agios Gordios'],
    warnings: ['Za mokra označeno jako problematické.'],
    timeFromHotel: null,
    mapsQuery: 'Myrtiotissa Beach, Korfu',
    sources: [],
    verify: [
      {
        what: 'Ověřit přístup, parkování, sestup a aktuální charakter pláže.',
        sp: 'SP:87–88',
        source: null,
      },
    ],
    sp: 'SP:70, SP:87–88, SP:122, SP:353',
  },
  {
    id: 'barbati-beach',
    canonicalName: 'Barbati Beach',
    czName: null,
    category: 'plaz',
    subcategory: null,
    tier: 'must-see',
    area: 'severovychod',
    why: 'Ruční seznam. Severovýchodní pobřeží v linii Nissaki – Kaminaki – Barbati – Ipsos.',
    wow: null,
    userPriority: null,
    visitDuration: null,
    bestPartOfDay: null,
    weather: null,
    transport: [],
    accessDifficulty: null,
    parking: null,
    combinesWith: ['Nissaki / Kaminaki / Barbati / Ipsos'],
    warnings: [],
    timeFromHotel: null,
    mapsQuery: 'Barbati Beach, Korfu',
    sources: [],
    verify: [],
    sp: 'SP:71, SP:91, SP:120, SP:210',
  },
];

/**
 * Doplní mapový bod z `coords.generated.ts`. Chybí-li záznam, karta zůstane bez bodu —
 * nikdy se nedosazuje odhad (SOURCE_PACK ř. 498).
 */
function withGeocode(seed: PlaceSeed): Place {
  const g = GEOCODED[seed.id];
  if (!g) {
    return {
      ...seed,
      coords: null,
      coordsStatus: 'chybi-ve-zdroji',
      coordsNote: 'Mapový bod zatím nebyl dohledán.',
      coordsSource: null,
      coordsQuery: null,
      coordsCheckedAt: null,
    };
  }
  return {
    ...seed,
    coords: g.coords,
    coordsStatus: g.coordsStatus,
    coordsNote:
      g.coordsStatus === 'overene'
        ? null
        : 'Mapový bod se nepodařilo jednoznačně dohledat — Navigovat otevře vyhledávání podle názvu.',
    coordsSource: g.coordsSource,
    coordsQuery: g.coordsQuery,
    coordsCheckedAt: g.coordsCheckedAt,
  };
}

/** 13 ručních must-see z části 6 SOURCE_PACKu, s doplněnými mapovými body. */
export const MUST_SEE: Place[] = MUST_SEE_SEEDS.map(withGeocode);

/** Celý katalog. Zatím obsahuje pouze 13 ručních must-see z části 6; doplní se v dalších krocích. */
export const PLACES: Place[] = [...MUST_SEE];
